### PR TITLE
Migrated asp.net core best practice to performance article & moved code to samples

### LINKED ISSUE #14605: Migrate AspNetCoreDiagnosticScenarios/AspNetCoreGuidance.md
Move 
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.md under **Test, debug, and troubleshoot** 
image

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #14605

[Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.1&branch=pr-en-us-14678#avoid-using-synchronous-readwrite-overloads-on-httprequestbody-and-httpresponsebody)

What was done:
Migrated: https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AspNetCoreGuidance.m@
to : performance-best-practices.

Light edit and moved all code snippets into a samples project (3.0).

Project does not compile yet.  @Rick-Anderson will take over for next steps.

### CODE REVIEW

**Comment by wadepickett** [comment]
Fixing the code snippet links and topic links....

**Comment by wadepickett** [comment]
@Rick-Anderson, should be in proper shape now for what you plan to do with this on the next step.  Let me know if you need anything or I didn't do this how you wanted.  Thanks.

**Comment by Rick-Anderson** [comment]
@wadepickett  I moved your commits to #14734

**Comment by wadepickett** [comment]
This was moved to branch directly off of aspnet/AspNetCore.Docs instead of my fork since Rick is also going to work on it.

**Pull request closed without merging**
