### PR TITLE
Cleared up some instructions with file paths

### PR DESCRIPTION
**Pull request by LouisT123**
1).At the beginning: line 16 -included file path for correct index method

2).At line 89 - included file path

3).At line 130 -included file path for correct index method

### CODE REVIEW

**Comment by LouisT123** [comment]
fixes issue #13598

**Comment by LouisT123** [comment]
fixes issue #13595

**Comment by LouisT123** [comment]
@Rick-Anderson Can you review the PR and merge it?
/cc: @anangaur
Thanks for the help so far!

**Comment by Rick-Anderson** [comment]
Thanks for the PR. Nice improvement.

**Comment by Rick-Anderson** [comment]
@LouisT123  BTW
`fixes issue #13595` doesn't close the issue, you need `fixes #13595`

**Comment by LouisT123** [comment]
> @LouisT123 BTW
> `fixes issue #13595` doesn't close the issue, you need `fixes #13595`

I see, I'm still new to making PR's thank you for closing it

**Pull request merged**
