### PR TITLE
Integration Testing topic+sample update for 3.0

### LINKED ISSUE #13353: Integration Testing update to 3.0
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13353

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1&branch=pr-en-us-14265)

* Are there new integration testing concepts/API for 3.0? I focus on the following items and don't add new content outside of 3.0 project updates. If there's nothing new on the framework side and if the following items sound ok, this PR doesn't require engineering review (unless you want to look).
* Whole-topic versioning on this one.
* A few minor language/description nits.
* New 3.0 sample confirmed working.
* Made two enhancements to the test for `Post_DeleteMessageHandler_ReturnsRedirectToRoot`. I make these updates to both the 2.x and 3.x sample apps:
  * Delete the records in the dB and reseed the dB for the test. We end up with one, non-duplicated set of seeded records this way regardless of other tests running and changing the dB.
  * I also select the first button of the `panel-body` `div` instead of grabbing a named button from the form. `QuerySelector` in AngleSharp uses takes a "first or default" grab for the element requested. Since the `id` values of the buttons are arbitrary, the updates here are robust for the test going forward ... it just grabs the first button of the div and doesn't try to find a named button of the whole form, where there's also a "Delete All" button (that we don't want to accidentally grab for this test).

### CODE REVIEW

**Comment by javiercn** [comment]
@guardrex Can you make sure we cover this comment in the update? https://github.com/aspnet/AspNetCore/issues/13918#issuecomment-532162945

**Comment by javiercn** [comment]
The doc update looks good. It might be a good idea for someone in the EF team to provide guidance on how to setup and initialize the database for integration tests. @divega or @ajcvickers can probably help here.

In the past a common approach was to use the in memory Db, but as an alternative I believe in memory SQL Lite could be used.

No matter what the approach is, ultimately its a matter of replacing services.

**Comment by divega** [comment]
> The doc update looks good. It might be a good idea for someone in the EF team to provide guidance on how to setup and initialize the database for integration tests. @divega or @ajcvickers can probably help here.

I volunteer @bricelam. I hope he can take a look or find someone else in the team.

**Comment by guardrex** [comment]
@javiercn Can I open a new issue for the additional updates and we go ahead and merge this?

I'm 🏃😵😅 for the next two weeks with 3.0 priority issues. I'd like to put the additional work (changing the dB and changing the app's environment) on the October sprint. I'll try to work them together (one issue).

Cross-references (just so I don't lose them) ...

* **Testing with SQLite** - https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite
* **Testing with InMemory** - https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory

**Comment by javiercn** [comment]
@guardrex Sounds good to me.

**Comment by guardrex** [comment]
@Rick-Anderson I'm going to open a new issue for the new work shortly. We can go ahead with our review+merge here now.

**Comment by stevo-knievo** [comment]
I would like to say thanks guys @guardrex @jodavis @divega. I really appreciate it.

**Comment by pedropablo** [comment]
This fixed the error in the test, but it doesn't solve the fact that the test is running on the db in Startup instead the db setup in ConfigureWebHost...

From some other issue linked in this whole WebApplicationFactory<TStartup> mess, I found this snippet

`         var descriptor = services.SingleOrDefault(d => d.ServiceType == typeof(DbContextOptions<ApplicationDbContext>));
                if (descriptor != null)
                {
                    services.Remove(descriptor);
                }
`

that seems to fix it (at least in the old _guardrex/int-test-30_ branch), placed just before adding the new AddDbContext with the InMemoryDatabase. But is that correct? Does it have some collateral am I not seeing?

Thanks!

**Comment by javiercn** [comment]
@pedropablo The docs have been updated to reflect the proper way to do it. This is how we mock the database on the Identity UI tests and we haven't had a problem with it.

**Comment by pedropablo** [comment]
That's not the proper way to do it. Check the latest comments on #9956 you are using whatever is configured in the real project not what you setup in the WebApplicationFactory.

**Pull request merged**
