### PR TITLE
Update routing.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes https://github.com/dotnet/docs/issues/15141

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@CeciAc  please review.
cc @guardrex

**Comment by guardrex** [comment]
Is this a test? ... is the plan to apply this to all docs mentioning "Blazor"?

**Comment by Rick-Anderson** [comment]
> Is this a test? ... is the plan to apply this to all docs mentioning "Blazor"?

Not really a test, just need approval from @CeciAc  this is the right syntax. Once approved, you'll do all of them.

**Comment by mairaw** [comment]
I'd recommend approving it after @CeciAc reviews it and checking the result of the localized page and then do the global change. We tried using this in a topic in .NET and it didn't work because of the formatting surrounding the words.

**Comment by Rick-Anderson** [comment]
@JasonCard  approved this, so let's see if that fixes the problem. @guardrex  hold off doing the rest of the docs until we confirm it works.

**Pull request merged**
