### PR TITLE
Update Blazor router in docs (preview 9)

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Updates for preview 9

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
@guardrex OK, rebased

**Comment by SteveSandersonMS** [comment]
What's the process - should I merge it now, or do you?

**Comment by guardrex** [comment]
I'm at the :muscle: gym ... yes, u can merge now.

**Comment by SteveSandersonMS** [comment]
Thanks, done.

**Pull request merged**
