### PR TITLE
Format Razor example in overview as cshtml

### PR DESCRIPTION
**Pull request by kimsey0**

### CODE REVIEW

**Comment by guardrex** [comment]
@kimsey0 If you agree with the terms, please sign the CLA :point_up:. We can't accept the PR without it. Thanks.

**Comment by kimsey0** [comment]
Oh, I thought it was just the Microsoft CLA, which I've already signed. I'll have a look at the .NET Foundation one.

**Comment by guardrex** [comment]
@kimsey0 I can make the changes on another PR if you don't want to sign the CLA. Did you decide not to sign it?

**Comment by kimsey0** [comment]
@guardrex, I have to get my employers acceptance for the CLA. For speed and ease, put the changes in another PR.

**Comment by guardrex** [comment]
Oh, ok. I understand. We can wait. I'd rather see you get credit here for making a contribution.

**Comment by kimsey0** [comment]
I'll get back when I have any updates.

**Comment by kimsey0** [comment]
@guardrex, I finally got to sign the CLA. Could you reopen this?

**Pull request merged**
