### PR TITLE
Update intro.md

### LINKED ISSUE #16897: Doesn't mention Database First approach
This article only explains Razor with EntityFrameworkCore using the Code First approach which assumes that you're creating a new database or tables for the application. It ignores the Database First approach where you're creating an application for an existing database. While EntityFrameworkCore doesn't implement all of the wizards that .Net EntityFramework does, it is possible to generate the data models from an existing database. See the article at: https://www.entityframeworktutorial.net/efcore/create-model-for-existing-database-in-ef-core.aspx. Substitute this for the portion of the article that manually creates the data classes (to follow this example you'll have to manually create the SQL Server database / tables instead), then just continue on with the scaffolding. Of course, change the database connect string in the appsettings.json file to point to your database (to match this example, the database name has to be 'SchoolContext'). Works fine and avoids having manually create a bunch of matching data models for a preexisting, possible complex, database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #16897

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Great links but that's not enough to help someone just getting started follow the tutorial using db first. I could add those links to the issue and ask folks to add additional help in the issue.

**Comment by tdykstra** [comment]
What about the getting started EF Core tutorials -- any chance we could resurrect those?  Do you know why they were deleted?  They were great for getting started or refreshing your memory after not doing EF Core for a while.  I needed to remember how to scaffold a model some time ago and ended up going to a 3rd party site for a tutorial because the EF Core official docs tutorial was gone.

**Comment by Rick-Anderson** [comment]
Can you open an issue with that question in the EF docs repo? I think they're getting a new PM soon.

**Comment by Rick-Anderson** [comment]
My guess is:

* Many  customers prefer DB first.
* It's not that hard to do DB first with your amazing tutorial. We just need a seperate doc with an outline of the instructions. We could then point to the db first doc.

**Pull request merged**
