### PR TITLE
Fix error "Not all code paths return a value in lambda expression of type"

### LINKED ISSUE #16698: Code Error - Multiple calls to UseOwin, grouped together.
Existing example: 
app.UseOwin(pipeline =&gt;
{
    pipeline(async (next) =&gt;
    {
        // do something before
        await OwinHello(new OwinEnvironment(HttpContext));
        // do something after
    });
});

Error Message: Not all code paths return a value in lambda expression of type 'Func&lt;Func&lt;IDictionary&lt;string, object&gt;, Task&gt;, Func&lt;IDictionary&lt;string, object&gt;, Task&gt;&gt;'

Suggestion: 

            var serviceProvider = app.ApplicationServices;
            var httpContextAccessor = serviceProvider.GetService&lt;IHttpContextAccessor&gt;();
            
            app.UseOwin(pipeline =&gt;
            {
                pipeline((next) =&gt;
                {
                    return async (environment) =&gt; {
                        // do something before
                        await OwinHello(new OwinEnvironment(httpContextAccessor.HttpContext));
                        // do something after
                    };
                });
            });

PS:  I don't know if the way I'm getting the HttpContext is the best way, if not, please correct me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34916983-6cf6-590e-0762-df0fe4e4f52c
* Version Independent ID: 1bf5bce0-c571-296e-1e8a-896af7068499
* Content: [Open Web Interface for .NET (OWIN) with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/owin.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/owin.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Marusyk**
Add possible solution to make a code working.

Fixes #16698

Please review,
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
Please see update

**Comment by Tratcher** [comment]
Did you paste this code into an app and make sure it resolved the error? It still doesn't look right.

**Comment by Marusyk** [comment]
yes

**Comment by Marusyk** [comment]
No errors in VS

Screenshot_3

**Comment by Tratcher** [comment]
Here's a more useful version of the sample:
```
app.UseOwin(pipeline =>
{
    pipeline(next =>
    {
        return async environment =>
        {
            // do something before
            await next(environment);
            // do something after
        };
    });
});
```

**Comment by Marusyk** [comment]
Great, thanks. I'll fix that

**Comment by Rick-Anderson** [comment]
@Tratcher  @Marusyk  Thanks!

**Pull request merged**
