### PR TITLE
Fix non-async ToListAsync example code.

### LINKED ISSUE #16795: Incorrect code?
The third example block shows: 
``` C#
public IEnumerable<Product> GetOnSaleProducts() =>
    _context.Products.Where(p => p.IsOnSale).ToListAsync();

```
Shouldn't the return type here be `Task<IEnumerable<Product>>` ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #16795.

### CODE REVIEW

**Comment by wrkettlitz** [comment]
The async/await is redundant. 
``` C#
public Task<IEnumerable<Product>> GetOnSaleProducts() =>
    _context.Products.Where(p => p.IsOnSale).ToListAsync();
```

**Comment by serpent5** [comment]
> The async/await is redundant.
> 
> ```cs
> public Task<IEnumerable<Product>> GetOnSaleProducts() =>
>     _context.Products.Where(p => p.IsOnSale).ToListAsync();
> ```

No, it isn't. Give it a try without. 😄

**Comment by wrkettlitz** [comment]
Tolistasync returns Task<List<Product>>. List<> implements IEnumerable<>, therefore there is an implicit cast  possible from List<> to IEnumerable<>. So a value of Task<List<Product>> can be used as a return value for Task<IEnumerable<Product>>

**Comment by wrkettlitz** [comment]
Be sure to remove both async and await keywords

**Comment by serpent5** [comment]
> Be sure to remove both async and await keywords

I strongly encourage you to try your suggestion. It won't compile.

**Comment by wrkettlitz** [comment]
What is the error?

**Comment by scottaddie** [comment]
I'd recommend using what @serpent5 has proposed in this PR, which is the following:

```csharp
public async Task<IEnumerable<Product>> GetOnSaleProducts() =>
    await _context.Products.Where(p => p.IsOnSale).ToListAsync();
```

Let's ask @rynowak what he thinks.

**Comment by rynowak** [comment]
I'm fine with what's in the PR.

Both of the following are correct:

```C#
public async Task<IEnumerable<Product>> GetOnSaleProducts() =>
    await _context.Products.Where(p => p.IsOnSale).ToListAsync();
```

```C#
public Task<IEnumerable<Product>> GetOnSaleProducts() =>
   _context.Products.Where(p => p.IsOnSale).ToListAsync();
```

The second one is more performant under certain circumstances, but many would argue that the first case is easier to understand and maintain.

Either way, the original sample wouldn't have compiled.

**Comment by serpent5** [comment]
The second example won't compile because of (I believe) covariance issues with `Task<T>`.

**Comment by rynowak** [comment]
Ah! well-spotted. I agree that the sample code should compile 😆

**Comment by serpent5** [comment]
Sorry, I was a little pressed for time when I commented earlier.

Just for completeness: The issue is that `Task<List<T>>` is not assignable to `Task<IEnumerable<T>>`. Adding `async`/`await` changes the semantics around how the `Task` wrapping works, which makes the compiler happy. I did also reason that, even without this issue, using `async`/`await` in a docs topic like this would be a safer bet.

**Comment by scottaddie** [comment]
Thank you for your help on this PR, @serpent5!

**Pull request merged**
