### PR TITLE
chore: Remove link locale

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
I'll just leave it for now. If you want to fix the "here" links and the locales you can
PS: If you enable https://github.com/apps/docs-content-validation these links would get flagged when PR'd

**Comment by guardrex** [comment]
I'm gonna leave them. Too busy. 🏃🏃🏃😅

**Comment by Rick-Anderson** [comment]
@nschonni see my changes

**Comment by nschonni** [comment]
@Rick-Anderson the abosolute links also make sense. The other "here" comment was about the SEO/Screen Reader friendlyness of the link text https://docs.microsoft.com/en-us/contribute/how-to-write-links#link-text

**Pull request merged**
