### PR TITLE
[Blazor] Prerendering + reconnect

### LINKED ISSUE #11836: [Preview 5] Prerendering with reconnect
We should add docs for the prerendering + reconnect feature.
* Describe how it works.
* Define the limitations.
* Talk about scale-out.

### PR DESCRIPTION
**Pull request by javiercn**
[EDIT by @guardrex to provide fixes link]

Fixes #11836

@danroth27 to validate the terminology that I used.

### CODE REVIEW

**Comment by guardrex** [comment]
This is for #11836?

After review and sign-off by PU, do you mind if I move the content to a new PR as opposed to creating a PR for this (with for example the TOC work required)? It's faster. I'll attribute the work to you (i.e., the byline).

**Comment by javiercn** [comment]
@guardrex Whatever works for you 😃

**Comment by javiercn** [comment]
Yep, this if or #11836

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore.Docs/pull/12872.

**Pull request closed without merging**
