### PR TITLE
Clarified where to run terminal commands

### LINKED ISSUE #13591: Need clarification on where to call terminal commands
Clarification on where to call the terminal commands would be helpful: "Make sure you are using the terminal for the RazorPagesMovie project. Right click the project name in the design/layout bar go to Tools&gt;Open in Terminal" [Add required NuGet packages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac#add-required-nuget-packages-1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac#add-a-database-context-class)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by mattielee**
Fixes #13591

### CODE REVIEW

**Comment by mattielee** [comment]
@Rick-Anderson Can you review the PR and merge it?
/cc: @anangaur

**Comment by Rick-Anderson** [comment]
review URL https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&branch=pr-en-us-13592&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
@mattielee  see my commit.

**Comment by mattielee** [comment]
Looks good, thank you!

**Pull request merged**
