### PR TITLE
[WIP] Social without Identity - Updates

### PR DESCRIPTION
**Pull request by serpent5**
@Rick-Anderson

Still a work-in-progress for now, but I thought it might be useful to create a draft PR to show where I'm at. The main thing that's outstanding is the explanation of the `DefaultScheme`, `DefaultChallengeScheme`, etc (I know, I know, that's the main part :stuck_out_tongue_closed_eyes:). I'll address that in the next commit, which I'm hoping to get to in the next day or two.

Feedback on what I have so far is, of course, very much appreciated. I've borrowed content from other topics and tried to follow conventions I've found there as best as I can.

### CODE REVIEW

**Comment by serpent5** [comment]
Sorry, I didn't mean to break a build :disappointed:. What did I do wrong?

**Comment by Rick-Anderson** [comment]
@scottaddie  how do we fix **This branch is out-of-date with the base branch**

**Comment by Rick-Anderson** [comment]
@scottaddie how do we fix This branch is out-of-date with the base branch
cc @tdykstra @guardrex

**Comment by tdykstra** [comment]
If it were me, I'd rebase on current master and force push.

**Comment by serpent5** [comment]
I branched from `rick-anderson/social/without/identity`, so I don't think I can rebase on `master` as the changes I've made here sit on top of @Rick-Anderson's branch and not `master`. I could be wrong...

I guess that trying to PR into a non-`master` branch is rare, but I wasn't sure if there was another way to go about it.

**Comment by tdykstra** [comment]
I don't know see how you could have gotten out of sync with Rick's branch as it appears to have been inactive for more than a month, but can you rebase on it instead of on master?

**Comment by serpent5** [comment]
It all looks like it's in-sync. I'm trying to rebase onto the latest from Rick's branch and I get:

> Current branch serpent5-12091 is up to date.

I'll see if I can dig a little deeper and find out more about what's going on...

**Comment by tdykstra** [comment]
It might be worth making a new branch and a new PR -- if the same thing happens we can assume it's a  problem in our build system and we can submit a request to investigate.

**Comment by serpent5** [comment]
Ok, I'll do that. Thanks for your help and suggestions.

**Pull request closed without merging**
