### PR TITLE
Changed png file to mac ui

### LINKED ISSUE #13581: Picture Does Not Correspond with instructions
Not tutorial breaking but the image in Visual Studio for Mac is the same as the Windows one for this section: [Add a view](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio-mac#add-a-view)  The instructions are still correct though. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio-mac#add-a-view)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by LouisT123**
Fixes #13581

### CODE REVIEW

**Comment by LouisT123** [comment]
@Rick-Anderson Can you review the PR and merge it?
/cc: @anangaur

**Comment by Rick-Anderson** [comment]
This will cause merge conflicts with #13556
We need to figure out how to get these fixes without too many merge conflicts
/cc: @anangaur

**Comment by LouisT123** [comment]
@Rick-Anderson It would be great if you could include my updated image in your pull request.

**Comment by Rick-Anderson** [comment]
@LouisT123  I'll S&M   #13556 today and let you know. You can add the new image (two places now) in a new PR.

**Comment by Rick-Anderson** [comment]
@LouisT123 hold off on more PR's to this series for a couple hours. I'll S&M this series and let you have at it. I'll work on something else until you're done. 
/cc: @anangaur

**Comment by LouisT123** [comment]
> @LouisT123 hold off on more PR's to this series for a couple hours. I'll S&M this series and let you have at it. I'll work on something else until you're done.
> /cc: @anangaur

Alright Thanks!

**Comment by Rick-Anderson** [comment]
@LouisT123  I'll be done in an hour. https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio-mac
Is really important if you want to review that one. You might ask /cc: @anangaur

**Comment by Rick-Anderson** [comment]
@LouisT123  looks like no merge conflicts
I'll merge this. Does the change fix both 3.0 and 2.2?

**Comment by Rick-Anderson** [comment]
@LouisT123  I'm done with this series for now so you can keep working on it.
PR  #13589 adds this change to the 3.0 version

**Pull request merged**
