### PR TITLE
access HttpContext through HttpContextAccessor

### LINKED ISSUE #12564: access HttpContext through HttpContextAccessor in ASP.NET Core 3.0
Hello,

I found problem when I converted app from .NET Core 2.2 into 3.0.
In **3.0** is `context.Resource` not anymore of type **AuthorizationFilterContext**, but instead **Microsoft.AspNetCore.Routing.RouteEndpoint**. Is there anything I'm missing (some changes in configuration or some other place)?
If did really changed, is there any way to redirect from handlers?
Any help is greatly appreciated.

```cs
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                                                      T requirement)
{
    var resource = context.Resource;     // 2.2 - AuthorizationFilterContext
                                         // 3.0 - RouteEndpoint

    if (context.Resource is AuthorizationFilterContext mvcContext) // in 3.0 results in null
    {
    }
}
```

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #12564

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@serpent5  please review

**Comment by Rick-Anderson** [comment]
@serpent5 can you suggest a better wording?

**Comment by serpent5** [comment]
How about something like this?:

> ### Accessing MVC request context in authorization handlers
> 
> When using endpoint routing, authorization handlers no longer receive an instance of `AuthorizationFilterContext` in the `AuthorizationHandlerContext.Resource` property when used with MVC routes. For more information, see [this GitHub issue](https://github.com/aspnet/AspNetCore.Docs/issues/12564).

The heading is the same as the one [here](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.0#accessing-mvc-request-context-in-handlers), just with "authorization" added as the context is different. Perhaps the section could go further up in this migration document, e.g. around "AddAuthorization moved to a different assembly" as it's related to authz.

Going forward, I think the section I've linked to above ([this one](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.0#accessing-mvc-request-context-in-handlers)) also needs to be updated for 3.0. The information from the linked issue (using `ControllerActionDescriptor` et al or `IHttpContextAccessor`) could go into that section and then the note added in this PR could link to that page rather than the GitHub issue. How does that sound?

**Comment by Rick-Anderson** [comment]
@serpent5  I agree. Should I close this PR and you can submit a PR?

**Comment by serpent5** [comment]
It’s up to you. I don’t think I can get to this before the weekend so feel free to use my suggestion above here and I’ll address the bigger changes later.

**Comment by Rick-Anderson** [comment]
@serpent5  no hurry.

**Pull request closed without merging**
