### PR TITLE
Removed images that are not referenced anywhere.

### PR DESCRIPTION
**Pull request by IEvangelist**
This PR removes images that are not referenced anywhere in the entire doc set and it excludes whitelisted images - such as those found in "wwwroot", "sample" and "snippet" directories. 😄

/cc @scottaddie, @guardrex, and @Rick-Anderson

image

### CODE REVIEW

**Comment by guardrex** [comment]
There are a couple here for topics that I wrote that I'll need to manually check.

I'm a bit 🏃😅 at the moment. I'll try to look tomorrow (Wednesday).

**Comment by Rick-Anderson** [comment]
No warnings/errors in the Docs Online Build Report, so the doc's won't be hurt.

**Comment by guardrex** [comment]
Sounds good. After this goes in and we go to live later, I'll :eyes: those few topics of mine and just make sure all is well.

**Comment by Rick-Anderson** [comment]
@guardrex  OK to S&M?

**Comment by guardrex** [comment]
I'll be free of a current task within 15 minutes. Let me run down my topic image changes here. It's a subset of perhaps just a half-dozen image removals here, so it won't take long. I'll ping back shortly.

**Comment by Rick-Anderson** [comment]
@guardrex  no hurry. S&M when you're ready.

**Comment by guardrex** [comment]
*DAH!* ... something that you think will take 15 minutes ends up taking a whole hour. *Welcome to software development in 2019!* :smile:

I'll take a look at this now and spot check a half-dozen of these. If they look good, I'll S&M.

**Comment by guardrex** [comment]
Spot checked over a dozen of these ... looks great. Thanks @IEvangelist! 🏍

**Pull request merged**
