### PR TITLE
Update forms-validation.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
PR of #15739

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0&branch=pr-en-us-15747)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  I don't understand how your commits got in this. 

image

**Comment by guardrex** [comment]
Sorry about that ... I hit the 🛌💤 sack a little early last night.

Notwithstanding that one commit there for Options (that is a little strange), I grouped the Blazor docs issues by PR for each document so that they would be easy for engineering to review and merge clean 🤞. We'll save a few 💵 in the process. It's all part of my *Beat Apple Docs!*:tm: program. 🚀:smile:

I recommend that you let me take your text here (along with any other changes that @pranavkm has on #15739, if present) and roll those onto my existing PR for this topic.

**Comment by Rick-Anderson** [comment]
> I recommend that you let me take your text here (along with any other changes that @pranavkm has on #15739, if present) and roll those onto my existing PR for this topic.

Agreed.

**Comment by guardrex** [comment]
Cool ... I'll take care of this very soon ... this afternoon for sure.

This content (this PR) is cross-linked, so I'll be able to find it. I'll close this and work your language here in on my PR.

**Pull request closed without merging**
