### PR TITLE
[WIP] updating RP tutorial to update scaffolding in vsmac

### PR DESCRIPTION
**Pull request by sayedihashimi**
I've updated the Razor Pages tutorial that starts at https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-3.1 to update the Visual Studio for Mac sections to show scaffolding.

We should not publish this until early Jan when Visual Studio for Mac 8.4 is released (that is when scaffolding is released). I've spoken to @jongalloway and he will work on submitting a PR for the MVC tutorial.

After we get these pages published we will create a Scaffolding doc in the Visual Studio doc set that points to these tutorials.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
cc @Rick-Anderson

**Comment by sayedihashimi** [comment]
@Rick-Anderson for this PR will a preview be generated? I had to modify some of the include files so would like to double check the rendered output.

**Comment by Rick-Anderson** [comment]
[Internal preview URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&branch=pr-en-us-16220&tabs=visual-studio)

@sayedihashimi  you can get the preview url from the details tab. It also shows errors and warnings

Warning | User | file-not-found | aspnetcore/tutorials/razor-pages/model.md | Invalid file link: 'model/_static/3/arpMac.png'. | 136
-- | -- | -- | -- | -- | --


image

**Comment by Rick-Anderson** [comment]
Use draft PR for not ready to merge PR's - when you can remember
image

**Comment by Rick-Anderson** [comment]
cc @jongalloway VS Mac PM extraordinaire

**Comment by sayedihashimi** [comment]
Thanks Rick, I will fix up the PR in the next couple of days.

**Comment by sayedihashimi** [comment]
I'm having some issues with this PR, some of my changes are not getting picked up for some reason. Going to close this and create a new one.

**Pull request closed without merging**
