### PR TITLE
Razor Components/Blazor access modifiers

### LINKED ISSUE #11010: Confirm/update private access modifier in RC topics+samples
There's at least one ... and probably a few more lurking in the code examples+sample apps. This happened because it was the case in the old Blazor engineering repo, examples, samples, etc.

@danroth27 to confirm that we need to always provide the `private` access modifier where currently in a handful of spots its defaulting to `private`.

Notes to self: Check Razor syntax topic. Confirm attribute location on same line or different line.

Note to self: Engineering PR with this.

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #11010 

😅 *Lot's 'o lines ... Took longer than I thought!*

* This (mostly) adds the explicit `private` access modifier.
* I confirmed samps are happy with the updates.
* Checked the Razor Syntax topic. It's 🎷 *Jamm'in!* 🎸.

👮‍♀️ **_Inconsistency Alert!_** 👮 We're using attributes (mostly) on the same line in RC/Blazor topics+samps but nowhere else (i.e., model attributes, attribute routing) in docs+samples.

*Inconsistent but short ...*

```cshtml
@functions {
    [Parameter] public string MyString { get; set; }
    [Parameter] public string AnotherString { get; set; }

    ...
}
```
*Consistent with docs+samples elsewhere but long ...*

```cshtml
@functions {
    [Parameter]
    public string MyString { get; set; }

    [Parameter]
    public string AnotherString { get; set; }

    ...
}
```

How do u want to play it? cc: @NTaylorMullen - *Thoughts?*

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
I'll let @danroth27 comment on this one 😄

**Comment by danroth27** [comment]
@guardrex We should be the `[Parameter]` attribute above the property.

**Comment by Rick-Anderson** [comment]
@danroth27 
> @guardrex We should be the `[Parameter]` attribute above the property.

Should that be

@guardrex We should have the `[Parameter]` attribute above the property.

**Comment by guardrex** [comment]
... and while ur answering ... add it here? I was about to move on to the EventCallback issue. I was planning to open a new issue for `[Parameter]` on a line and work it separately if that's what we're going to do.

**Comment by guardrex** [comment]
@Rick-Anderson Let's go ahead. The samps run and the changes are fairly straightforward here. I need this one merged in order to get on to the [EventCallback issue (aspnet/AspNetCore.Docs \#11243)](https://github.com/aspnet/AspNetCore.Docs/issues/11243).

I opened [Razor Components/Blazor [Parameter] attribute (aspnet/AspNetCore.Docs \#11913)](https://github.com/aspnet/AspNetCore.Docs/issues/11913) to deal with `[Parameter]` on its own line. Will dig into that later.

**Comment by danroth27** [comment]
Sorry about my typo 😝.

I was trying to say that instead of this:

```csharp
[Parameter] public string MyString { get; set; }
```

We should at some point switch to this:

```csharp
[Parameter]
public string MyString { get; set; }
```

**Comment by guardrex** [comment]
@danroth27 Gotcha ... opened https://github.com/aspnet/AspNetCore.Docs/issues/11913 to address it.

**Pull request merged**
