### PR TITLE
Deploy to Azure Apps update to 3.0

### LINKED ISSUE #11658: Strip logging extension versioned content at 3.0
At *Monitoring and logging* strip prior extension naming at 3.0 (Lines 81-91).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2#monitoring-and-logging)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #13339: Azure Apps Overview update to 3.0
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13339
Fixes #11658

I don't see any obvious changes for 3.0, except ..........

For logging extension coverage, we have ...

> ASP.NET Core apps deployed to App Service automatically receive an App Service extension, **ASP.NET Core Logging Extensions**. The extension enables logging integration for ASP.NET Core apps on Azure App Service.

1. The name didn't change to **ASP.NET Core Logging Integration**. I guess we'll strip that here. If that's still in the works, what's the ETA on it?
1. We say that the extension is automatically added, but I just spun up an App Service and didn't get it automatically. Should we **_not_** say it's automatic here?

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@shirhatti super short review please.  If nothing has changed for 3.0, no review needed.

**Comment by shirhatti** [comment]
> The name didn't change to ASP.NET Core Logging Integration. I guess we'll strip that here. If that's still in the works, what's the ETA on it?

Name hasn't changed. It hasn't been on my radar so I assume it isn't happening.

> We say that the extension is automatically added, but I just spun up an App Service and didn't get it automatically. Should we not say it's automatic here?

It only gets "automatically" when you right-click publish from Visual Studio. The docs should ask you to install the site extension for other scenarios

**Comment by guardrex** [comment]
Thanks @shirhatti ... I'll address your feedback tomorrow (Thursday).

**Comment by guardrex** [comment]
Feedback from https://github.com/aspnet/AspNetCore.Docs/pull/13933#issuecomment-528151939 addressed on last commit.

**Pull request merged**
