### PR TITLE
AddControllers and Endpoint Routing migration

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by danroth27** [comment]
@RickAndMSFT Can we get this reviewed and merged in for the release tomorrow?

**Comment by guardrex** [comment]
@Rick-Anderson I'm free if you want me to make an edit pass on it.

**Comment by scottaddie** [comment]
@guardrex Go ahead. The more eyes, the better.

**Comment by guardrex** [comment]
Sure thing ... in place edit tho. I don't have ⌚️ time for "\`\`\`suggestions" remarks. :smile: lol

**Comment by guardrex** [comment]
I hope ...

>  The more eyes, the better.

... is code for **_two :beer: com'in my way_**. :smile: lol

That's a single pass. I'd recommend one more by me or another doc :cat2:.

**Comment by Rick-Anderson** [comment]
@rynowak see my changes in #12034 - If they're OK, merge into this PR and we can merge to live when you're ready.

@guardrex  and anyone else, no changes to this PR, make changes in #12034

**Comment by rynowak** [comment]
Thanks @Rick-Anderson ! Merged your changes into mine.

**Comment by guardrex** [comment]
@tdykstra Unless there's anything else here, this can go in as well ... it will catch this merge to live with the redirects PR.

**Pull request merged**
