### PR TITLE
Azure Custom Script Extension for web farms

### LINKED ISSUE #14520: Hosting Bundle Installer/ANCM deployment in web farm environments
We don't address how to deploy/maintain the hosting bundle/ANCM in web farm environments. The [dotnet-install PS script](https://docs.microsoft.com/dotnet/core/tools/dotnet-install-script) can't help OOB.

* @shirhatti @Tratcher, what do you currently advise?
* Should we provide guidance (or link to something) on the subject in this topic?

cc: @mtirion (asked about this offline)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be127bb-755c-98ab-d7fb-b3f50687857f
* Version Independent ID: 9562d8c0-563d-21ca-e802-80f9b99689ff
* Content: [Host ASP.NET Core in a web farm](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/web-farm.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/web-farm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #14520

Probably the best that we can do/offer at this time. If you would like an issue to flesh this out later with explicit instructions for the hosting bundle, I can open that and work it later when there's less on my plate. However, their docs look good. :ear:

### CODE REVIEW

**Comment by guardrex** [comment]
@Tratcher Another quick one. 🏃 ... That text comes right from **_their description_** of the Azure Custom Script Extension.

**Comment by Tratcher** [comment]
This is a better question for @shirhatti. He's on vacation at the moment, but this can wait for him to get back.

**Comment by guardrex** [comment]
@shirhatti U available yet? If not, no worries, this can wait.

**Comment by guardrex** [comment]
@shirhatti Minimize it to an *Additional Resource*? See the last commit. :point_up:

Otherwise, we can close. Devs can find this with a Google/Azure docs search.

**Comment by shirhatti** [comment]
:shipit:

**Pull request merged**
