### PR TITLE
Updated SignalR tutorial screenshots for VS2019 and 3.0 GA

### LINKED ISSUE #13919: Update screenshot(s) and code in SignalR tutorial to use Visual Studio 2019
@donhuvy ...

&gt; Need update screenshot SignalR tutorial use Visual Studio 2019

@BrennanConroy ...

&gt; If you select 3.0-preview you'll see updated docs with VS 2019.
&gt;
&gt; I'm not sure what the policy is for updating previous docs with new VS. We probably are going to keep 2.2 as-is, otherwise every new tooling will need a ton of updates to docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#create-a-web-project)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

### PR DESCRIPTION
**Pull request by wadepickett**
[Review 3.0 version with new screenshots](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&branch=pr-en-us-14755&tabs=visual-studio)

Fixes #13919 

Updated all screenshot to match VS 2019 + ASP.NET Core 3.0GA.  No text changes required in its topic, tested.  Libman graphic did not require an update.

### CODE REVIEW

**Comment by wadepickett** [comment]
@Rick-Anderson, ready for review, thanks.

**Comment by wadepickett** [comment]
@Rick-Anderson, Many thanks for the general rules to follow on monikers and screenshot versions.  Very helpful.
For this doc:
In this case, the .md file already followed the moniker rule so I will not make a change for that in the .md.
In the case of the old version of screenshots, this doc already has a 2.x and 3.x folder for screenshots:  The 2.x screenshots were properly left in tact.  I only replaced the ones in the 3.x folder with 3.0 screenshots.  So those are already following the guildance as well.
For the code: I missed the difference in templates for services.Configure in the startup.cs and will account for those in 3.x vs 2.x.  Thanks!

**Comment by wadepickett** [comment]
Ready for review.

**Comment by Rick-Anderson** [comment]
@wadepickett  I think Brady has done this update in #14764
Can you review #14764 and probably close this PR?

**Comment by wadepickett** [comment]
@Rick-Anderson,  I will review Brady's on #14764 .  Yes, if it is a duplicate (ugh) then I will close this one and help him finish that one.

**Comment by scottaddie** [comment]
I merged the PR from Brady. Now that 3.0 has shipped, can we remove the pre-3.0 content? I think our strategy all along has been to support only the latest stable version in tutorials. Thoughts, @Rick-Anderson?

**Comment by Rick-Anderson** [comment]
> can we remove the pre-3.0 content

Yes

**Comment by wadepickett** [comment]
@Rick-Anderson and @scottaddie  ,  I will remove all prior versions to 3.0 and add the code fix missing from the #14764 merge this morning an anything else I see that need updated.  Creating a new tracking issue for it and will also note it here once I identify all that needs to change in just a bit...

**Comment by wadepickett** [comment]
Closing per Rick since we ended up with duplicate work to #14764.   Will open a new issue using the latest merge of 14764 to master.

**Comment by wadepickett** [comment]
@scottaddie ,  I took your request to remove pre-3.0 content to mean to remove anything before 3.0 GA.   So 2.2, 3.0 Preview, etc.  It just dawned on me that you might have meant a much more narrow scope.  Were you  1. Just referring to 3.0 content related to the 3.0 preview releases to remove or any version including 2.x   Or 2. Saying to remove all prior content not focused on the 3.0 GA or later such as, 2.x, etc?

**Pull request closed without merging**
