### PR TITLE
Update custom-model-binding.md

### LINKED ISSUE #14186: Add polymorphic
do it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #14186

When approved, this will merge into #14122

[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.2&branch=pr-en-us-14187#polymorphic-model-binding)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@pranavkm Do you have a full sample someplace I can incorporate? If not, I'll add that part.

**Comment by pranavkm** [comment]
I don't think I do. I wrote this in a sample app and don't have it around anymore. The specific bit I wanted to highlight was adding to `ValidationState` since that determines how validation works.

**Comment by Rick-Anderson** [comment]
No problem, I'll crank out the form to post data.
Can I merge this into your PR now?

**Comment by pranavkm** [comment]
Go ahead 👍

**Pull request merged**
