### PR TITLE
Model Binding 3.0 + Custom JSON

### LINKED ISSUE #15705: Add a section that shows how to customize the model bound using [FromBody] and System.Text.Json
This is common enough that it should have an explanatory section.

Use this code-snippet as a starting point
```csharp
    [ApiController]
    [Route("[controller]")]
    public class CustomJsonController : ControllerBase
    {
        [HttpPost]
        public IActionResult Post([FromBody] DataModel model) => Ok(model);

    }

    public sealed class DataModel
    {
        [Required]
        public ObjectId ObjectId { get; set; }
    }

    [JsonConverter(typeof(ObjectIdConverter))]
    public struct ObjectId
    {
        public ObjectId(int id) => Id = id;

        public int Id { get; }
    }

    internal class ObjectIdConverter : JsonConverter<ObjectId>
    {
        public override ObjectId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => new ObjectId(JsonSerializer.Deserialize<int>(ref reader, options));

        public override void Write(Utf8JsonWriter writer, ObjectId value, JsonSerializerOptions options) => writer.WriteNumberValue(value.Id);
    }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0#frombody-attribute)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by serpent5**
Fixes #15705.

Going for the same approach as before for visibility.

cc @Rick-Anderson

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@serpent5  let me know when you're ready for me to post a public view of the build.

**Comment by serpent5** [comment]
@Rick-Anderson I’m going to approach this differently in a new PR. I’ve been rebuilding the sample from the ground up but doing that is going to create a lot more review work, etc. So I’ll just copy the 2.2 sample and upgrade it to 3.0 instead.

**Comment by Rick-Anderson** [comment]
@serpent5  but we want to keep the 2.2 version. Might be best to create a new sample.

**Comment by serpent5** [comment]
@Rick-Anderson Yeah. I meant copy the current 2.2 sample into a new 3.x folder and then upgrade that copied version to 3.0 in-place

**Pull request closed without merging**
