### PR TITLE
chore: Update allowed HTML elements

### PR DESCRIPTION
**Pull request by nschonni**
li and ul are sometimes needed in Markdown tables

### CODE REVIEW

**Comment by tdykstra** [comment]
Let's wait a bit on this, while I check if HTML lists within MD tables is considered acceptable for docs.

**Comment by guardrex** [comment]
It's the only way btw ... tried MD first and it ended in :cry: tears. This was asked-and-answered earlier: HTML is *dissuaded* but not outlawed. In those cases where I used lists, they worked out well ... look good ... organized that content well.

**Comment by tdykstra** [comment]
Turns out we have a lot longer list of whitelisted HTML tags, and we should make MarkdownLint match it:

The following HTML elements, organized by category, are whitelisted:

Type | Elements  
---------|---------
Headings     |  h1, h2, h3, h4, h5, h6
Prose     |  p, div, blockquote
Formatted     |   pre
Inline     |     b, i, strong, em, tt, code, ins, del, sup, sub, kbd, samp, q, var
Lists     |   ol, ul, li, dl, dt, dd
Tables     | table, thead, tbody, tfoot, tr, td, th
Breaks     |   br, hr

**Comment by guardrex** [comment]
**_Sweet!_** ... only when needed, of course. MD is nice but a bit too constraining sometimes imo.

**Comment by nschonni** [comment]
The alternate would be to turn on the rule and use `<!-- markdownlint-disable MD033 -->` in the areas/files that it's required

**Comment by tdykstra** [comment]
I would vote for either disabling the rule entirely or adding the whitelisted elements.

**Comment by scottaddie** [comment]
I vote for adding the whitelisted elements.

**Comment by nschonni** [comment]
> I would vote for either disabling the rule entirely or adding the whitelisted elements.

This is one of the rules were it's not a good idea to disable it. EX:
`List<T>` renders to  "List<T>" and swallows the `<T>` without escaping

**Comment by tdykstra** [comment]
I used the other PR only for disabling selected rules, so I"ll add a commit to this PR for the rest of the allowed HTML elements.

**Comment by tdykstra** [comment]
@nschonni Thanks for getting the work on this rule started and for all your contributions to making our Markdown more consistent!

**Pull request merged**
