### PR TITLE
Google et al without Identity + sample.

### PR DESCRIPTION
**Pull request by serpent5**
Initial work for #12091.

I've created a sample app that demonstrates login and logout using Google + Cookies without Identity. I've also created an almost-empty docs page that just contains links to the relevant source snippets that I intend to discuss within the page.

I'm submitting this early as a draft PR so that I can get feedback on two things:

1. The location and naming of the docs page.
2. The sample app. I don't expect to add anything else to this so I'd appreciate eyes on whether it's a good basis for the docs page.

I intend for the docs page to focus on Google specifically but to acknowledge and link to the other providers accordingly.

### CODE REVIEW

**Comment by guardrex** [comment]
A couple of passing remarks:

* Idk if either alternative was considered ...
  * Use a modified version of the Additional Claims sample for this. (However, note that a big PR is modifying that one now on https://github.com/aspnet/AspNetCore.Docs/pull/11950.)
  * No sample ... just call out the changes that are required in one or a few snapshot files. If this is possible, it would be great to not have *one more sample* to update every release. We can't keep up as it is. :cry:
* Nit: We *try* to make GH happy about ending files on a blank line. See the *Privacy.cshtml.cs* file ... add a return to the last line. It may have even come from the template that way. I'll check the engineering repo. If they need a PR for it, I'll put that in with them.
* Since this subject matter pertains to social login, I think @tdykstra will want it in `aspnetcore/security/authentication/social/`, and the UID would get the *social* segment. Because of that, I would recommend that having the word "social" again in the URL isn't required. The last segment can be *without-identity* (or something else that doesn't include "social"). He'll come on and let u know what he wants to do on these points.
* Name the sample app *SampleApp*. We put them into a *samples* (plural) folder and then inside of a *2.x* folder for this version. That way , we can add a *3.x* folder with another *SampleApp* folder later. The samples link in the intro of the topic will go like this (but hold changes tho until u hear from Tom).

  > \[View or download sample code](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/social/without-identity/samples) (\[how to download](xref:index#how-to-download-a-sample))

  ... and the full path to a file would be ...

  > aspnetcore/security/authentication/social/without-identity/samples/2.x/SampleApp/SomeFile.xxxx

  Ellipses in the TOC? I'm surprised. Still tho ... my half-penny's worth ... something more like this would be better ...

  ```
  - name: Social authentication without Identity
    uid: security/authentication/social/without-identity
  ```

* For most samples we're drop static assets to slim the repo, but these authn/authz ones really suffer without them. We've been leaving the static assets (CSS, JS) in these authn/authz samps, so you're good there. :+1: However, you can drop the cookie policy bits from the sample. Not needed; we're dropping it from samples now; and IIRC, engineering is dropping it in the future anyway (although, they might keep it for auth templates ... not sure).

**Comment by serpent5** [comment]
Thanks for the detailed feedback @guardrex - this is exactly why I decided to get visibility on this as early as possible. I’ll wait for the others to respond accordingly before I look into making changes, as you’ve suggested. It seems like I might already be looking at a do-over so perhaps I’m being a bit too ambitious with contributing on this one... 😟

**Comment by guardrex** [comment]
I hope they say (and u think it can be done) that we don't need a full sample ... just snapshots. I'm still trying to get back to our 2.0 and 2.1 samples (and I think there are even 1.x samples! *Yikes!*). 🏃😅 .... this is one case where *The more the merrier!* definitely **_does NOT apply_**. :smile: lol

**Comment by guardrex** [comment]
I sent in a patch PR on the line endings. That will speed us up over here on docs. I always stop and add them as I go with a new sample. https://github.com/aspnet/AspNetCore/pull/10192

**Comment by Rick-Anderson** [comment]
>For most samples we're drop static assets to slim the repo,

Just the minified and a few others that aren't used in local dev. That's automatic via *.gitignore*

**Comment by guardrex** [comment]
I think the scenario where things get ugly is working in development. There's no fallback for the non-min versions of static assets.

**Comment by Rick-Anderson** [comment]
>I think the scenario where things get ugly is working in development. There's no fallback for the non-min versions of static assets.

Just use *.gitignore*. That's our standard. The debug assets are trivial.

>My approach totally removes them (in non-auth sample cases). My samps always look marvelous! 😄 .... hopefully, they run ok, too! lol

Don't do that. Just depend on *.gitignore*

**Comment by guardrex** [comment]
> The debug assets are trivial ... Just depend on .gitignore

They aren't. In dev, static assets won't be present on the dev's machine for a downloaded sample. The sample will look great here (on my machine) but when the dev downloads it from the repo (without non-min static assets) it will look like crap when they run it in development.

If you're saying to force the static assets into the repo with .gitignore, ok, but that defeats the goal of having slim samples.

https://github.com/aspnet/AspNetCore.Docs/issues/9186 is still open ... recommend that we get that figured out if there's still a misunderstanding on my part. I'm just going by what I thought we worked out there ... see DR's remark at https://github.com/aspnet/AspNetCore.Docs/issues/9186#issuecomment-432827970.

**Comment by serpent5** [comment]
@guardrex Are there any samples I can help bring up to 2.2 to try and lighten the load?

**Comment by guardrex** [comment]
> Are there any samples I can help bring up to 2.2 to try and lighten the load?

I defer to management on that.

**Comment by Rick-Anderson** [comment]
@serpent5 take a look at the issues and let me know what you'd like to do. It doesn't matter if the issue is currently assigned to someone else.

**Comment by serpent5** [comment]
What are the next steps for this?

**Comment by Rick-Anderson** [comment]
@serpent5 sorry. I'll start reviewing it today.

**Comment by serpent5** [comment]
That's fine. No need to apologise at all. I'm just checking in here as the comments went a bit off topic and I also wanted to make sure you know I'm still keen to try and get this done.

**Comment by Rick-Anderson** [comment]
@serpent5  what are the steps to get this working? This is what I tried:

`dotnet new webapp -o WebApp1 -au Individual -uld`

Remove `<partial name="_LoginPartial" />` from the layout file.

Update code to what you have. I run the code and click on the Privacy link, but a break point on `OnGetLogin` is never hit.

If we do this, I think we'd need to hook up the UI so you could sign-in/sign-out

**Comment by serpent5** [comment]
You don't want to create the project with `-au Individual -uld` as that sets up Identity, which I expect is conflicting with the `AddAuthentication` stuff I've added. `OnGetLogin` is a replacement for what would normally be the "Account/Login" route in MVC/RP and is triggered within the sample I created by clicking on a login link that I added to the navbar to mimic what it would look like with Identity.

If you run the sample app as is, it should all work. If you click "Privacy", it won't trigger the `OnGetLogin` page but it will send you straight over to Google. `OnGetLogin` and `OnPostLogoutAsync` are handlers that get triggered from the navbar in the sample, which I added in an attempt for consistency with the Identity approach. You can see this in the `_LoginPartial` I added and modified in the sample.

I'd intended for the docs to be a guide that called out the sections most relevant to the auth stuff, but to just mention that the navbar in the sample app is linked to those page handlers. I'm happy to change the approach to a step-by-step guide that starts with an empty app and talks through the start to finish process. Alternatively, we can ditch the page handlers and just detail adding the auth stuff and applying the `[Authorize]` attribute. This could be based on the webapp template or could be more basic, starting from the empty template.

**Comment by Rick-Anderson** [comment]
I like your approach.  I think it's best to keep it as simple as possible.

Let me add some instructions and we'll see what the security folks say.

**Comment by Rick-Anderson** [comment]
Moved to #12444

**Comment by Rick-Anderson** [comment]
@serpent5 Using postman, I post to https://localhost:44369/Index to logout but I get back 400 bad request.

When I'm not sign-ed in. I have a break-point (BP) on
```
public IActionResult OnGetLogin()
{
    return Challenge(new AuthenticationProperties
    {
        RedirectUri = Url.Page("/Index")
    });
}
```
I redirect too google to approve, but I never hit the above BP.

**Comment by serpent5** [comment]
@Rick-Anderson If you're using Postman, it's likely 400ing due to the antiforgery token being absent. The endpoint would also need the `Logout` handler to invoke the logout code, i.e. `https://localhost:44369/Index?handler=Logout`. Otherwise, it's just going to render the view without first logging out.

`OnGetLogin` was only there for the case where we have a "Sign in" button, in order to issue a challenge explicitly. If we don't have a button/link for signing in, we don't need to include a `OnGetLogin` handler.

Thanks for your patience here. I had intended to flesh out the docs page after the sample was reviewed, but things have gone in a different direction to what I originally anticipated, so I realise that what I've provided isn't very clear now.

**Comment by Rick-Anderson** [comment]
@serpent5  thanks. I'll remove the  `OnGetLogin` handler.  I think all we need is a mechanism to logout.

**Pull request closed without merging**
