### PR TITLE
Update Blazor WebAssembly sample to go at pair with the new WebAPI sample

### LINKED ISSUE #14771: Blazor WebAssembly sample references a previous version of the API tutorial
From @juandelacruz23 ...

Blazor docs references [this sample](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/3.x/BlazorSample), and it says it uses the [API](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi) from the WebApi tutorial. I found some problems running them:

- The new api version uses endpoints called api/TodoItems, while the Blazor sample calls api/Todo
- The web api uses the same port than blazor, and trying to run it crashes at first, should changing it be documented? Along with enabling CORS.
- There are some css files missing.
- A file/class was renamed in the web api, but it's references on Program.cs weren't, so it fails to compile.

I almost solved all of it, it's ok to make a pull request? Or would this be solved by another person? 🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by juandelacruz23**
Fixes #14771
@guardrex please check it out :)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@juandelacruz23  can you sign the CLA. We can't review until you do so,

**Comment by juandelacruz23** [comment]
@Rick-Anderson ready to go 👍

**Comment by guardrex** [comment]
Thx @juandelacruz23 ... I'll take a look at this over the weekend.

Please add a commit that includes yourself to the end of Line 13 ...

```
By [Luke Latham](https://github.com/guardrex), [Daniel Roth](https://github.com/danroth27), and [Juan De la Cruz](https://github.com/juandelacruz23)
```

... change the `https://github.com/juandelacruz23` link destination to your blog (or website) if you have one. Use whatever endpoint is best for you.

It's great to have your significant contribution to the docs ... we **_greatly appreciate_** it. :tada: Pings on the topic will still come to me, so you won't be bothered by that. Please add yourself. There's no editorial policy on keeping the author byline or leaving you there across topic updates, so I don't know how long it will last. However for now, it can be a nice little career/resume add-on. Please add yourself to Line 13.

**Comment by juandelacruz23** [comment]
> 
> 
> Thx @juandelacruz23 ... I'll take a look at this over the weekend.
> 
> Please add a commit that includes yourself to the end of Line 13 ...
> 
> ```
> By [Luke Latham](https://github.com/guardrex), [Daniel Roth](https://github.com/danroth27), and [Juan De la Cruz](https://github.com/juandelacruz23)
> ```
> 
> ... change the `https://github.com/juandelacruz23` link destination to your blog (or website) if you have one. Use whatever endpoint is best for you.
> 
> It's great to have your significant contribution to the docs ... we **_greatly appreciate_** it. 🎉 Pings on the topic will still come to me, so you won't be bothered by that. Please add yourself. There's no editorial policy on keeping the author byline or leaving you there across topic updates, so I don't know how long it will last. However for now, it can be a nice little career/resume add-on. Please add yourself to Line 13.

My contributions to that file were minimal 😔 didn't too much on that because I didn't know exactly what was the "source of truth". If the guide should look more like the sample or vice versa.

If it still counts, I can put my name. If not, it's fine like that 👍 and if help is still needed to update the docs, I can work on it; just tell me which is the "source of truth" and what style should the writing have, because you said that some things would be more appropiate in a tutorial, and that this was just a reference topic.

**Comment by guardrex** [comment]
Not really "minimal" in the sense that you're making an important contribution to keeping the doc updated. We want to encourage devs to help keep the docs up-to-date. This is one way that we can do that. **_Add yourself to Line 13._** I really appreciate you working on this topic. I'm soooooo 🏃😅 ... just about burned out here. 😅 lol

**Comment by guardrex** [comment]
@juandelacruz23 👍 ...... I'll take a look this weekend and get back to you.

**Comment by guardrex** [comment]
Looks great ... thanks @juandelacruz23 ... it will go live shortly.

**Pull request merged**
