### PR TITLE
Update the choice text for a Blazor server-side experience.

### PR DESCRIPTION
**Pull request by britebit**
This text now matches the dialogue box in Visual Studio 2019 16.2.0 Preview 3.

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @britebit ... The current text is correct. The server-side experience should be called **Blazor (server-side)**. The "hosted" template is a client-side Blazor app hosted by an ASP.NET Core app.

Capture

**Comment by britebit** [comment]
Ahh .. my bad. I made an assumption about which option was server-side.  I think the docs still need updating. I downloaded the VS 2019 preview today and saw the options below. I think we need to change `Blazor (server-side)` to `Blazor Server App`. Would you agree? If so, I'll raise another PR.

image

**Comment by guardrex** [comment]
Yes, that's great. As you already surmised, I'm on 16.1.6 (not Preview). Let's do that right here and for `master` as you did given that we instruct the use of VS Preview for all Blazor apps at this time.

1. Search the entire repo for the text "Blazor (server-side)" ... five results across four files. One of them is in commented-out text for MS4Mac.
1. Replace those five instances with the new text.
1. Commit the updates back to this PR.

**Comment by guardrex** [comment]
If you agree with the CLA, sign the agreement :point_up:. We can't accept the PR without it.

**Comment by britebit** [comment]
Is this the one, or do I need to do something else?

> [CLA assistant check](https://cla.dotnetfoundation.org/aspnet/AspNetCore.Docs?pullRequest=13274)
> All CLA requirements met.

**Pull request merged**
