### PR TITLE
Update department model for MySql

### LINKED ISSUE #12259: The property 'Department.Budget' could not be mapped ?
## system environment
```
os: deepin linux 
ide: vscode 
netcore version: 2.2.203

database: mysql  server 
database version: Ver 14.14 Distrib 5.7.21, for Linux (x86_64) 
mysql drive: MySql.Data.EntityFrameworkCore/8.0.16
```
## error 
When I learn [ASP.NET Core MVC with EF Core - tutorial series](https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-mvc/?view=aspnetcore-2.2),  Then run the following command：
 
```
dotnet ef migrations add md2
```

## attempt
```
The addition of the [NotMapped] attribute to Budget 
in the Department.cs file was successful, 
but the Department table in the database had no Budget field.
```

### PR DESCRIPTION
**Pull request by JackLovel**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@tdykstra  I recommend we only add instructions for MySql, not to change the code.

**Comment by tdykstra** [comment]
@Rick-Anderson Agreed, a note about MySQL in the tutorial at the point the attributes are added, with no change to the sample app would be best.

**Comment by tdykstra** [comment]
@JackLovel  Would you like to submit a new PR with the MySQL note in the tutorial? If not, no problem, I'll do it.

**Comment by JackLovel** [comment]
> @JackLovel Would you like to submit a new PR with the MySQL note in the tutorial? If not, no problem, I'll do it.

thank reply me

**Pull request closed without merging**
