### PR TITLE
Missing an x in the port url

### PR DESCRIPTION
**Pull request by LouisT123**
Small fix here

### CODE REVIEW

**Comment by LouisT123** [comment]
@Rick-Anderson Morning! Can you review the PR and merge it?
/cc: @anangaur

**Comment by guardrex** [comment]
One thing that we've been doing around the repo is use braces with a plain placeholder name. Here's how that might look ...

> Run the app and enter the following URL: \`https://localhost:{PORT}/HelloWorld/Welcome/3?name=Rick\`

**Comment by LouisT123** [comment]
> One thing that we've been doing around the repo is use braces with a plain placeholder name. Here's how that might look ...
> 
> > Run the app and enter the following URL: `[https://localhost:{PORT}/HelloWorld/Welcome/3?name=Rick`](https://localhost:%7BPORT%7D/HelloWorld/Welcome/3?name=Rick%60)

Good suggestion, I'll try modifying the format to the one you suggested for the doc.

**Comment by guardrex** [comment]
btw - you can edit the file right here on the PR ... but if you want to make a new PR, that's ok, too. :+1:

**Comment by guardrex** [comment]
Re-open this ... flip over to **Files changed** ... click the three dots (upper-right-hand corner) ... and you can edit and make another commit to this PR.

**Pull request closed without merging**
