### PR TITLE
add cookie path

### PR DESCRIPTION
**Pull request by noctwolf**
It is recommended to add this line, compatible with applications deployed in IIS

### CODE REVIEW

**Comment by guardrex** [comment]
@Tratcher Isn't this the default if it isn't set?

https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Abstractions/src/CookieBuilder.cs#L103

**Comment by Tratcher** [comment]
Yes. Why are you setting it to the default value?

**Comment by noctwolf** [comment]
The instantiated here is the RequestPathBaseCookieBuilder class.
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Cookies/src/CookieAuthenticationOptions.cs#L15
Changed Path in the Build method of the RequestPathBaseCookieBuilder class
https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Core/src/RequestPathBaseCookieBuilder.cs#L21-L35

**Comment by noctwolf** [comment]
@Rick-Anderson @guardrex @Tratcher 
For the first time people using SSO, this is a trap

**Comment by Tratcher** [comment]
Ah, I forgot about those custom builders. Yes, this is a scenario that we should discuss and document but changing it in just this code sample isn't going to help. Please file a doc bug so we can make sure the SSO scenario is covered.

**Comment by noctwolf** [comment]
The file modified in this PR is already cookie-sharing.md
What should I do?

**Comment by guardrex** [comment]
Cookie options are first discussed here ...

https://docs.microsoft.com/aspnet/core/security/authentication/identity-configuration#cookie-settings

@noctwolf File an issue using the **This Page** feedback form at the bottom of that topic.

**Pull request closed without merging**
