### PR TITLE
Update Custom Model Binding to 2.1.

### LINKED ISSUE #16367: 2.1 UPDATE Model binding
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by serpent5**
Addresses #16319.
Fixes #16367

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@serpent5  nice work, thanks!

**Comment by serpent5** [comment]
@guardrex I think this affects #5495. I'm going to look at the linked issues next and then do a 3.1 update. I dunno if you want to wait until then before updating the sample-tracker. I'm just putting it on your radar for when you're back from ~working through your holidays~ being OOF. :smile:

**Comment by guardrex** [comment]
Thanks @serpent5 ... Since I'm not cross-linking to the PRs, I'll just update it in the tracking issue to 3.1 now. Well ... "now" = "Monday" :smile: lol ... I'm savoring my last two PTO days before 🏃 in January.

**Comment by serpent5** [comment]
> I'm savoring my last two PTO days before 🏃 in January.

Glad to hear it. You guys work too hard but what you do is great.

**Pull request merged**
