### PR TITLE
Typo in json config prevented me from running my app on Linux

### PR DESCRIPTION
**Pull request by armitagemderivitec**
Endpoints should have a lower case 'p' as per: 

https://github.com/aspnet/AspNetCore/blob/c288baf967ddb615162e71ad924bd14526194908/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs#L16

### CODE REVIEW

**Comment by guardrex** [comment]
hum 🤔 ... that's interesting because we doc "keys" as case-insensitive ...

> Configuration keys adopt the following conventions:
>
> * Keys are case-insensitive. For example, `ConnectionString` and `connectionstring` are treated as equivalent keys.

However, *yes* on the specific point. Let's match anyway.

@HaoK Does `GetSection` require case matching? If so, I'll need to do a tad of work on what we mean by "key" in the Configuration doc.

**Comment by armitagemderivitec** [comment]
With a capital P i get this error:
```
 System.InvalidOperationException: The endpoint Http is missing the required 'Url' parameter.
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConfigurationReader.ReadEndpoints()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: Unhandled Exception: System.InvalidOperationException: The endpoint Http is missing the required 'Url' parameter.
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConfigurationReader.ReadEndpoints()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
Jun 18 13:38:35 ip-32-0-32-123.ec2.internal derivitec-nuget[20016]: at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()

```

**Comment by guardrex** [comment]
hum ... interesting ... yeah, that's not what one would expect from the case change.

@HaoK will :eyes: that. He may direct u to open an engineering issue. Stand-by for his reaction.

After he looks, we'll merge this anyway. It is better to match, of course, so we thank u for sending the PR.

**Comment by HaoK** [comment]
This is an issue with Kestrel since its doing its own configuration binding/reading/parsing, cc @Tratcher

**Comment by HaoK** [comment]
But configuration.GetSection shouldn't be case sensitive, so it must be something else that is causing the case issue

**Comment by guardrex** [comment]
That's what I was thinking. I feel an *engineering investigation* might ensue. Should @armitagemderivitec open an issue in engineering and we can just proceed to merge this for docs?

**Comment by HaoK** [comment]
Yeah that's best, open an issue with the repro config and we can take a look

**Comment by guardrex** [comment]
@armitagemderivitec  Open an issue at ...

https://github.com/aspnet/AspNetCore/issues

... and describe that. Include the stack trace.

I'll go ahead with this. We want to match the casing no matter the underlying casing issue.

**Pull request merged**
