### PR TITLE
Add NCache coverage to the Distributed Caching topic

### PR DESCRIPTION
**Pull request by mohsinnasir**
Added NCache info in Prereqs
added NCache distributed cache sub section in the Idistibutedcache section

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @mohsinnasir ... I just have nits. It will be faster if I edit directly, then have you look at the changes to see if they look good. I'll ping you back in a bit.

**Comment by guardrex** [comment]
@mohsinnasir ... Your name isn't on your profile at https://github.com/mohsinnasir. What's your name? I'll add you to the author byline.

**Comment by guardrex** [comment]
@mohsinnasir ... I need your name for Line 13.

Check the updates. I don't trust the moniker ranges to indent the code cleanly under the last bullet point, so I include the steps in each range. I think that's the safest way to go.

**Comment by mohsinnasir** [comment]
> @mohsinnasir ... ~I need your name for Line 13.~ Added you on the byline as "Mohsin Nasir" ... sound good?
> 
> Check the updates and see if they're good.

i have seen the changes and they look fine

**Pull request merged**
