### PR TITLE
Update sdk.md

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
Could we move this document to a node under "Advanced"? Right not it's under Razor Pages, but it has content related to Blazor and MVC:

image

**Comment by guardrex** [comment]
Pinging @tdykstra for that :point_up: ❓

**Comment by tdykstra** [comment]
LGTM

**Comment by guardrex** [comment]
@pranavkm Make the change in the *toc.yml* file.

We'll need to make some nit edits before merging. Ping one of us for a pass when ur ready.

**Comment by guardrex** [comment]
The alternative is that one of us can create a PR to mod this with the updates, including the TOC change.

**Comment by Rick-Anderson** [comment]
@pranavkm  is this ready to S&M? I'll update *toc.yml*

**Comment by Rick-Anderson** [comment]
> Could we move this document to a node under "Advanced"? Right now it's under Razor Pages, but it has content related to Blazor and MVC:

Can I list it both places?

**Comment by tdykstra** [comment]
The official policy is not to allow multiple TOC nodes for one doc, so we avoid it except in cases where the discoverability need outweighs that policy.  It's up to you if that applies in this instance.

**Comment by pranavkm** [comment]
> @pranavkm is this ready to S&M? I'll update toc.yml

If the content looks good to you, feel free to merge it in.

**Comment by guardrex** [comment]
This required some nit updates and has a broken WARNING.

**Comment by Rick-Anderson** [comment]
I was going off @tdykstra  LGTM

**Comment by guardrex** [comment]
That's why I noted "We'll need to make some nit edits before merging" **after** he said that. :smile:

*My plan didn't work out so well!* :smile: lol

**Comment by guardrex** [comment]
Note that for the fixes, the versioning doesn't require 2.1, as the whole topic is versioned >=2.1.

**Comment by tdykstra** [comment]
>I was going off @tdykstra LGTM

I was responding to the question about TOC placement.

**Pull request merged**
