### PR TITLE
Updated for .netcore3

### PR DESCRIPTION
**Pull request by mavado83**
Package name changed from .netcore2.x to .netcore3

### CODE REVIEW

**Comment by guardrex** [comment]
@mavado83 If you agree with the terms, please sign the CLA :point_up:.

**Comment by guardrex** [comment]
Thanks @mavado83.

@BrennanConroy If these updates are good in principle, let's make sure we get a docs team pass on the layout. I'll take care of it after you :eyes:.

**Comment by BrennanConroy** [comment]
@guardrex Looks good

**Comment by guardrex** [comment]
Thanks ... I'll fix it up and get it merged.

**Pull request merged**
