### PR TITLE
Fixed two small typos in yesterday's changes

### PR DESCRIPTION
**Pull request by CamSoper**

### CODE REVIEW

**Comment by guardrex** [comment]
@CamSoper This link doesn't exist ... is that a topic *coming soon*?

xref:security/authentication/azure-ad-b2c-webapi

**Comment by CamSoper** [comment]
@guardrex Thanks, I missed that warning last night. I retired that doc so I need to change the remaining doc to remove that link.

**Comment by guardrex** [comment]
Oh, ok. I thought it was me there for a sec. I'm doing three things at once ...... gotta STOP 🛑 do'in that. :smile: lol

**Comment by CamSoper** [comment]
@guardrex Nah, that's how we keep life interesting for each other 😉

**Pull request merged**
