### PR TITLE
Reorder suggested CORS Middleware location

### LINKED ISSUE #13660: Method UseCors() has invalid position
If you put UseCors() method after UseAuthentication() and UseAuthorization(), everytime auth fails, CORS error will appear in browser too because web app never when through UseCors() method. I think UseCors() method should be called first. Correct me if i'm wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13660

Thanks @filipbekic01! 🏍

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@guardrex  - @scottaddie  is out. Did you verify this with PU?

**Comment by guardrex** [comment]
Unauthenticated preflight requests fail when CORS Middleware comes after Authentication Middleware.

This gets ugly here now because we don't also say that Static File Middleware has to come after CORS Middleware in scenarios where static files require CORS.

We sought to address this in a general way on https://github.com/aspnet/AspNetCore.Docs/issues/10839 because **_any_** middleware that may use CORS has to come after the CORS Middleware to work.

Perhaps, that PR (for the CORS topic) didn't go far enough. I did a quick search on the repo, and I don't see a single sample or text reference specifically for CORS and Auth Middleware ordering. I can open an issue to address it further in the CORS topic, but I'm 🏃 for a bit if you want me to work it.

For now, I'll ping for engineering. First tho, I'll try to touch this up for static files.

**Comment by guardrex** [comment]
*Ah!* ... no need for a new issue.

We can piggyback that little update on the existing 3.0 update for **_CORES_**. :smile:

**Comment by guardrex** [comment]
@anurse Do you have a sec to look? It's a quick one.

**Pull request merged**
