### PR TITLE
Correcting image url

### PR DESCRIPTION
**Pull request by sayedihashimi**
Minor fix to point to the correct image.

### CODE REVIEW

**Comment by sayedihashimi** [comment]
#sign-off

**Comment by Rick-Anderson** [comment]
@sayedihashimi  would you like me to push this to live now?

**Comment by sayedihashimi** [comment]
@rick-Anderson that would be great, thanks.

**Comment by Rick-Anderson** [comment]
Hold on, I need to fix your build error
see https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C8%5Cff1b9f40-00b1-57d9-58da-03fc9ac53777%5CPullRequest%5C202001080351253814-16458%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KT3tUhXMLb4qHm2VhBSxTleKeDAYK7o7Ng1hiWNcS%2Bs%3D&st=2020-01-08T03%3A47%3A38Z&se=2020-02-08T03%3A52%3A38Z&sp=r

**Comment by Rick-Anderson** [comment]
Found/fixed it.

**Comment by Rick-Anderson** [comment]
ok, LIVE IN 5 minutes

**Comment by sayedihashimi** [comment]
Thanks Rick

**Pull request merged**
