### PR TITLE
sample uses new beatpulse, so updated

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**
fixed doc according sample and new lib used in sample

### CODE REVIEW

**Comment by guardrex** [comment]
@dzmitry-lahoda Thanks ... BeatPulse is listed right at the top of that repo. There are a few more references that I updated on the last commit. I figure that the simplest thing to do is just use the one name, `AspNetCore.Diagnostics.HealthChecks` everywhere. Check my updates and see if you agree with the changes.

**Comment by guardrex** [comment]
I put the "BeatPulse" naming and link back, but I only added it to the NOTE where it talks about the lib not being supported by Microsoft. That way, it keeps their branding intact here.

**Comment by guardrex** [comment]
@unaizorrilla Would you like to review this PR?

**Comment by guardrex** [comment]
No response, so let's go ahead with this. Thanks @dzmitry-lahoda! :rocket:

**Comment by unaizorrilla** [comment]
Hi @guardrex

I’m sorry but I’m on different timezone!!

I read the PR and look good!

**Comment by guardrex** [comment]
Sorry about that ... I should've known. If you think it needs more work, let me know.

**Pull request merged**
