### PR TITLE
Update RazorPagesMovieContext.cs

### PR DESCRIPTION
**Pull request by imba-tjd**
Related to #16056

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
The 2.2 uses the original namespace.

**Comment by imba-tjd** [comment]
@Rick-Anderson I see, though the living article isn't showing `Data` even when I choose 3.1. Is this expected?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-a-database-context-class

图片

**Comment by Rick-Anderson** [comment]
That class need a `using RazorPagesMovie.Data;`

**Comment by imba-tjd** [comment]
Now as far as I understand, `RazorPagesMovieContext` is in `namespace RazorPagesMovie.Models` when [it's 2.2](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Data/RazorPagesMovieContext.cs) and in `namespace RazorPagesMovie.Data` when [it's 3.0](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30/Data/RazorPagesMovieContext.cs) but [model2.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/includes/RP/model2.md) only uses 2.2: `[!code-csharp[](~/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie22/Data/RazorPagesMovieContext.cs)]`

**Comment by Rick-Anderson** [comment]
See #16072

**Comment by imba-tjd** [comment]
OK. Maybe this PR(mine) should be closed since I changed 2.2

**Comment by Rick-Anderson** [comment]
No, it's in the Data folder, so it doesn't need that using.

**Pull request closed without merging**
