### PR TITLE
Update 22-to-30.md

### LINKED ISSUE #14602: UseAuthentication/UseAuthorization needs to be AFTER UseRouting but BEFORE UseEndpoints.
https://github.com/aspnet/AspNetCore/issues/14403
~@borland  please review~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #14602
@borland I meant please review this.

[Internal review url](https://review.docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-1.0&branch=pr-en-us-14603&tabs=visual-studio#migrate-startupconfigure)

### CODE REVIEW

**Comment by guardrex** [comment]
@Rick-Anderson Side-note on this one: IIRC, we have a bit in the DI topic on middleware ordering that may need a touch for this, too.

**Comment by borland** [comment]
Bit late sorry but LGTM

**Comment by Rick-Anderson** [comment]
@borland  thanks for bringing this to our attention. I wanted to get it online ASAP

**Comment by blowdart** [comment]
@pranavkm to review

**Pull request merged**
