### PR TITLE
Update razor-pages-start.md and mvc for vsmac

### PR DESCRIPTION
**Pull request by sayedihashimi**
This replaces my previous PR #16220, which is to update the Razor Pages tutorial to update the Visual Studio for Mac sections.

WIP.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&branch=pr-en-us-16390&tabs=visual-studio)

**Comment by jongalloway** [comment]
I accidentally marked this as "Ready for Review" - can we undo that?

**Comment by sayedihashimi** [comment]
#hold-off

**Comment by Rick-Anderson** [comment]
> I accidentally marked this as "Ready for Review" - can we undo that?

I've done that a dozen times and so have lots of other folks. It's one of GitHubs top requests to be able to make it draft again. Right now you can't make it Draft after you've made it ready.

WIP in the title will let everyone know.

**Comment by jongalloway** [comment]
MVC Tutorial for VS for Mac is ready for review, too: [Internal Review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&branch=pr-en-us-16390&tabs=visual-studio-mac)

**Comment by Rick-Anderson** [comment]
@sayedihashimi  @jongalloway  Let me know when I can IS&M (squash and merge), then merge to live?

**Comment by jongalloway** [comment]
I think we need to hold this PR for the Visual Studio for Mac 8.4 release, right @sayedihashimi?

**Comment by sayedihashimi** [comment]
Yes we are waiting until we release 8.4. @Rick-Anderson we will reach out to you.

**Comment by sayedihashimi** [comment]
#sign-off

@Rick-Anderson we are ready to get this merged. Our release goes out tomorrow, can we get it merged & published today?

cc @jongalloway

**Pull request merged**
