### PR TITLE
UE Localization Extensibility doc + fix links

### LINKED ISSUE #13639: UE Localization Extensibility doc + fix links

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13639

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/localization-extensibility?view=aspnetcore-2.1&branch=pr-en-us-13640)

* Had a few minutes here to make a quick 🏃 pass while fixing two bad links.
* Add XREF API links.
* Narrow the code blocks.
* Made a few lingo and section heading touches here and there.

### CODE REVIEW

**Comment by hishamco** [comment]
LGTM.. thanks a lot

**Comment by hishamco** [comment]
When this will be online?

**Comment by guardrex** [comment]
@hishamco I'll shoot master to live now. It won't take long after that.

**Comment by guardrex** [comment]
@hishamco Done ... https://github.com/aspnet/AspNetCore.Docs/pull/13654.

**Comment by hishamco** [comment]
Thanks a lot

**Pull request merged**
