### PR TITLE
Update SignalR tutorial to 3.0 - startup.cs - additional screenshots

### LINKED ISSUE #13919: Update screenshot(s) and code in SignalR tutorial to use Visual Studio 2019
@donhuvy ...

&gt; Need update screenshot SignalR tutorial use Visual Studio 2019

@BrennanConroy ...

&gt; If you select 3.0-preview you'll see updated docs with VS 2019.
&gt;
&gt; I'm not sure what the policy is for updating previous docs with new VS. We probably are going to keep 2.2 as-is, otherwise every new tooling will need a ton of updates to docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio#create-a-web-project)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

### PR DESCRIPTION
**Pull request by wadepickett**
Fixes #13919 

[Review Link](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&branch=pr-en-us-14812)

- Updated startup.cs to use latest template.
- Removed 2.x content from SignalR.md, screenshots and codes examples per @Rick-Anderson 
- Updated screenshots : Show new default localhost ports in running example, show 3.0 (GA) in new project dialog, show latest DevTools (F12)
- Removed extra </div> in index.cshtml

### CODE REVIEW

**Comment by wadepickett** [comment]
...need to fix a moniker yet in SignalR.md

**Comment by wadepickett** [comment]
@bradygaster, just want to make sure you didn't miss this since we were both in the files for different items to update on the same tutorial.  This was building off of your merge yesterday.

**Comment by wadepickett** [comment]
@bradygaster , does this seem OK?  Can I merge?  I want to make sure I am not messing up anything else you had in play for this doc as I try to help update.

**Comment by bradygaster** [comment]
yes! sorry about that, I thought i'd reviewed this - no issues.

**Comment by wadepickett** [comment]
Thanks!

**Pull request merged**
