### PR TITLE
Hosted Services updates for 3.0

### LINKED ISSUE #12841: Update Background tasks article for 3.0 (Generic Host)
Migrate sample app to 3.0 (Generic Host) and put snippets in 2.2 vs. 3.0 moniker blocks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&tabs=visual-studio#additional-resources)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### LINKED ISSUE #14381: WebHost in ASP.NET Core 3 startup order (code shows IHostedService tasks before IApplicationStartup notified)
On this page it says: 

> When using the Web Host, StartAsync is called after the server has started and IApplicationLifetime.ApplicationStarted is triggered. When using the Generic Host, StartAsync is called before ApplicationStarted is triggered.

However the code from the latest v3.0.0-preview9 shows that the `StartAsync` for hosted services from `WebHost` is still called before `ApplicationStarted`: https://github.com/aspnet/AspNetCore/blob/v3.0.0-preview9.19424.4/src/Hosting/Hosting/src/Internal/WebHost.cs#L154

This is the better and expected behavior by the way, looks like it's just the documentation that needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #14381
Fixes #12841

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1&branch=pr-en-us-14417)

* Whole topic versioning.
* Thanks @manigandham ... In your honor, the official example calls out the `VideosWatcher` :eyes:.
* New 3.0 sample.
  * Based on the new Worker Service template, and we can add the VS4Mac instructions now.
  * Nice upgrades to the sample thanks to anurse advice. 💵 *In Nurse We Trust*:tm: 💵 :beers:
* Let's drop the 2.x Generic Host sample. That was just a demo (i.e., never linked into the topic), and the Generic Host has churned quite a bit since 2.x. I don't think we should show that at all.
* Let's not have a 3.x Web Host-based sample.

Note: In VSC's external terminal, the sample does respond to keystrokes to add queued work items. However, the app doesn't respond to Ctrl+C. It used to work when the 2.x sample was created and Ctrl+C works in a command shell for this 3.x app, but there's been a VSC regression somewhere along the way. I'll open an issue with VSC to investigate.

### CODE REVIEW

**Comment by anurse** [comment]
> In Nurse We Trust

Benedict Cumberbatch, playing Sherlock Holmes, is wearing a suit and top hat. He looks at a person off-camera and tips his hat

**Comment by guardrex** [comment]
@anurse Update on the `Ctrl+C` and `UseConsoleLifetime` situation: I just opened https://github.com/microsoft/vscode/issues/81322. We're ok to proceed on the PR because I tell readers to run the sample app in a command shell. I'm going to open a new issue in a sec connected to that VSC issue to fix this up later when we get a final answer/solution.

**Comment by guardrex** [comment]
@anurse Do you still need time to look this over, or should I go ahead and call for docs team review?

**Comment by anurse** [comment]
I think I'm happy with it

**Comment by guardrex** [comment]
> I think I'm happy with it

@anurse  I informed our docs management that *plausible deniability* is an important characteristic of the documentation process that might be used in certain cases where deliberations lead to the apparent need for qualitative distinctions that can't be potentially dealt with under ephemeral circumstances and the underlying complexities of the subject being described can't be completely adjudicated clearly at the time said subject was addressed.

They were *very happy* with that position and embraced it wholeheartedly. We're all good. :+1:

So ......... @Rick-Anderson ... We're ready.

**Pull request merged**
