### PR TITLE
 ODATA Security & expand

### LINKED ISSUE #12115: Create an ODATA security doc
Create an ODATA security doc
Port over [Security Guidance for ASP.NET Web API 2 OData](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-security-guidance)

### LINKED ISSUE #12306: Add OData Expand
Add OData Expand

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #12115
Fixes  #12306
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/odata-security?view=aspnetcore-2.2&branch=pr-en-us-12150)
[OData Expand](https://review.docs.microsoft.com/en-us/aspnet/core/web-api/advanced/odata-expand?view=aspnetcore-1.0&branch=pr-en-us-12150)

Moving to https://github.com/MicrosoftDocs/OData-docs/issues/69

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@FIVIL  please review. See [Public review URL](https://www.dropbox.com/s/qnfrlca4gse9cbw/Security%20Guidance%20for%20ASP.pdf?dl=0) Might get stale

From my testing all that works without the EDM except the EDM stuff at the end of the article. Is that correct?

**Comment by FIVIL** [comment]
@Rick-Anderson 
Yes, I  also tested them, all of them work just fine (paging and ordering on indexed columns tested in production under load)
however, we didn't mention `Expand()` which enables querying related data and therefore it causes SQL joins and can be super demanding. I wanted to add `Expand()` related stuff to my second sets of articles but if you are creating security-related docs I assume we should mention it.

**Comment by Rick-Anderson** [comment]
@FIVIL  push a commit to this branch with `Expand`

**Comment by FIVIL** [comment]
@Rick-Anderson Sure thing. (I just need a bit time to finalize my work on them)

**Comment by Rick-Anderson** [comment]
@FIVIL No hurry. We all greatly appreciate your valuable contributions.

**Comment by FIVIL** [comment]
@Rick-Anderson 
i created a new PR for `$expand` samples, i submitted PR to this branch `2/ODATA/security/ra` not the `master` branch.
 https://github.com/aspnet/AspNetCore.Docs/pull/12191

**Comment by FIVIL** [comment]
@Rick-Anderson 
I finished `expand` documentation.
https://github.com/aspnet/AspNetCore.Docs/pull/12150

**Comment by Rick-Anderson** [comment]
@hassanhabib please review

**Comment by hassanhabib** [comment]
> @hassanhabib please review

@Rick-Anderson  looks good to me - great stuff! thank you for doing this!

**Comment by Rick-Anderson** [comment]
@FIVIL please review my changes to expand

**Comment by FIVIL** [comment]
@Rick-Anderson 
They are fine with me.

**Comment by Rick-Anderson** [comment]
@danroth27 please recommend a reviewer for ODATA.

**Comment by Rick-Anderson** [comment]
@serpent5  How do I update these sample to 3.0 with endpoint routing?  Note the sample/doc will not got in this repo, it's going to https://github.com/MicrosoftDocs/OData-docs/issues/69

**Comment by Rick-Anderson** [comment]
What would be nice is having Startup2.2.cs and a 3.0 version. Maybe use `#if 2_2` in Main.

**Comment by serpent5** [comment]
> How do I update these sample to 3.0 with endpoint routing?

It doesn't look it's possible right now. See https://github.com/OData/WebApi/issues/1748#issuecomment-537531980 and the related thread.

**Comment by Rick-Anderson** [comment]
@serpent5  thanks! I'll move the 2.2 samples over.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/MicrosoftDocs/OData-docs/pull/74

**Pull request closed without merging**
