### PR TITLE
Add IsIPv4MappedToIPv6 support to example

### PR DESCRIPTION
**Pull request by KuanWeiTW**
Add IsIPv4MappedToIPv6 to example for better support

### CODE REVIEW

**Comment by KuanWeiTW** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@jkotalik please review or suggest a review for this nice short fix
```
if (remoteIp.IsIPv4MappedToIPv6)
                {
                    remoteIp = remoteIp.MapToIPv4();
                }
```

**Comment by KuanWeiTW** [comment]
@jkotalik 
The old code supports both ipv6 and ipv4, but not ipv4 in ipv6 format
If a client ip is ::ffff:192.0.2.128 and the whitelist is 192.0.2.128, it would be blocked since SequenceEqual return false in if-statement.
However, I believe the right behavior is to let ::ffff:192.0.2.128 pass the filter, right?

**Comment by KuanWeiTW** [comment]
@jkotalik Hi, do you have any suggestions? Should I resolve the conflict caused by #15304 ?

**Comment by Rick-Anderson** [comment]
> Should I resolve the conflict caused by #15304 ?

Yes please.

**Comment by KuanWeiTW** [comment]
Hi @Rick-Anderson and @jkotalik , I've finished the resolving conflicts work, please help to review this PR again. Thanks a million. 👍

**Comment by Rick-Anderson** [comment]
@KuanWeiTW  much appreciated. Keep them coming.

**Pull request merged**
