### PR TITLE
URL Rewriting topic+sample update for 3.0

### LINKED ISSUE #13338: URL rewriting update to 3.0
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f7c61-a9fa-bd34-001d-217477874bb6
* Version Independent ID: 9c48da92-af90-3fc1-fde0-c3f74fa88510
* Content: [URL Rewriting Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/url-rewriting.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/url-rewriting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13338

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&branch=pr-en-us-13862)

* Sample update to 3.0 confirmed working.
* Whole-topic versioning.
* There are no significant content updates here. Fortunately, it ✨ *Just Works!*:tm: ✨ for 3.0.

### CODE REVIEW

**Comment by rynowak** [comment]
@anurse  - who should help look at this?

**Comment by guardrex** [comment]
@mikaelm12 is my co-author on this and worked on the original topic with me.

**Comment by guardrex** [comment]
https://github.com/aspnet/AspNetCore/commits/master/src/Middleware/Rewrite/src

Not much there ... I don't think we explicitly call out limiting domains for `RedirectToWwwRule`, but that would be fairly quick to determine from API docs and IntelliSense.

**Comment by mikaelm12** [comment]
Yup! @guardrex is right. I'll review this in full on Monday!

**Comment by guardrex** [comment]
@mikaelm12 There are no content changes on the PR, and the sample is unchanged except for the update to 3.0. If there aren't framework changes (breaking changes, new/modified API), then you don't need to perform an in-depth review unless you want to.

**Comment by mikaelm12** [comment]
> any 3.0 changes to URL rewriting?

Nope

**Pull request merged**
