### PR TITLE
Apache configuration to Host Blazor webassembly

### LINKED ISSUE #14859: Apache configuration
Add Apache2 (httpd) example configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by harrison314**
[EDIT by guardrex to add issue number]

Fixes #14859

Adding Apache2 (httpd) example configuration to *Host and deploy* for Blazor webassembly.

Example is tested on CentOs7.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @harrison314 ...

Is it ok to break the long line for `AddOutputFilterByType`? We try to keep code lines <=85 characters so that we don't have horizontal scrollbars in the topics. If it isn't possible to break that line as I did on the update commit, I'll revert that back to one line.

**Comment by guardrex** [comment]
Open an issue for major changes prior to submitting work. Management needs to be able to track everything outside of small patches and bug fixes via issues. No worries tho ... I opened one ... we're good here. :+1: :smile:

**Comment by harrison314** [comment]
> Is it ok to break the long line for AddOutputFilterByType? We try to keep code lines <=85 characters so that we don't have horizontal scrollbars in the topics. If it isn't possible to break that line as I did on the update commit, I'll revert that back to one line.

I fixed in commit fcb258b7161a0b0d713d2217e83f3b41b39f86f1 and tested it.

> Open an issue for major changes prior to submitting work. Management needs to be able to track everything outside of small patches and bug fixes via issues. No worries tho ... I opened one ... we're good here

Thank you for the info.

**Comment by guardrex** [comment]
Thanks @harrison314 ... that's perfect. We sometimes must allow a long line (and thus end up with a scrollbar), but it's good for us if we can keep them short like that.

**Comment by guardrex** [comment]
ping @danroth27

**Comment by guardrex** [comment]
I can't say either ... I have *limited* experience. Do you want to ping Sourabh to take a look?

**Comment by guardrex** [comment]
@Rick-Anderson This wasn't reviewed by @shirhatti yet. Of course, we could let the community let us know if it 💥 later.

**Pull request merged**
