### PR TITLE
Update jsonpatch.md

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by Paul-Dempsey** [comment]
Looks good -- that's a very useful addition!  If this doc is going to the Open Publishing system for docs.microsoft.com, the proper notation for a note is:

```markdown
> [!NOTE]
>text of note
```

**Comment by Rick-Anderson** [comment]
@Paul-Dempsey  we don't like excessive chrome and tend to not even uses `Note:`,  and rarely ```markdown
> [!NOTE]
>text of note
```

**Comment by Rick-Anderson** [comment]
Updating in #15404

**Comment by pranavkm** [comment]
Looks great. Feel free to merge at your convenience

**Pull request merged**
