### PR TITLE
Update Microsoft.dotnet-openapi.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Merge to #13941 when ready.
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/microsoft.dotnet-openapi?view=aspnetcore-3.0&branch=pr-en-us-14002)

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  where should this go in the TOC?

**Comment by scottaddie** [comment]
Let's also get the [help option](https://github.com/aspnet/AspNetCore/blob/66de493473521e173fa15ca557f5f97601cedb23/src/Tools/Microsoft.dotnet-openapi/src/Application.cs#L37) documented.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can we merge this into your branch.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  what  I need to change so we can merge this into your branch?

**Pull request merged**
