### PR TITLE
Update DirectoryStructure

### LINKED ISSUE #16722: Framework-dependent executable is missing from list
The list of files generated by `dotnet publish` for an FDD is missing the executable:
[framework-dependent executable is the default for the .NET Core SDK 3.x CLI](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#framework-dependent-executable).

Because the filename extension of an executable is platform-dependent, it wouldn't fit neatly in the current format of

> {ASSEMBLY NAME}.{EXTENSION}

It could potentially use parentheses or a double dagger to mention this and also refer to the FDE section I linked above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566f8ed0-217e-5125-b0f7-6d93c3a145c1
* Version Independent ID: 9fa94395-eff8-3b12-c2d5-c1c6d4142378
* Content: [ASP.NET Core directory structure](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/directory-structure.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/directory-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #16722

* Add to the list only for >=3.0 (version the table for this change) ...

  ```html
  <li>{ASSEMBLY NAME}{.EXTENSION} (*.exe* extension on Windows, no extension on macOS or Linux)</li>
  ```
* Show via the defaults: FDD is the default for <3.0, while FDE is the default for >=3.0. The >=3.0 version of the table will show FDE. The <3.0 version of the table to show FDD.
* Add the abbreviations (FDE, FDD, and SCD) to the table.
* Executable extension is *.exe* on Win. No extension for macOS and Linux.
* **Not** cross-linking the .NET Core doc [Publish .NET Core apps with the CLI](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli) because it's in the node under the more general landing topic (linked multiple times here) that pertains to app deployment in .NET Core docs. Readers will find it when they navigate over there.

Thanks @TomVeltmeijer! 🏍

### CODE REVIEW

**Comment by anurse** [comment]
> * Assumes that the executable is _.exe_ xplat (macOS and Linux, too), which I think is correct.

It is not. The executable is `[appname].exe` on Windows and `[appname]` (no extension) on macOS and Linux.

**Comment by guardrex** [comment]
I did a publish to check, and IIRC that's what I saw in the output. My test was probably bad. 🙈

**Comment by guardrex** [comment]
*Yep!* ..... I **hosed** my own test! I see it now .......

Capture

**Comment by guardrex** [comment]
@Rick-Anderson ... hold off on review until tomorrow. There's something else I want to fix in this topic. I'll do it in the morning and re-ping u for a review.

**Comment by guardrex** [comment]
To make this coverage more *Crossplatishable*:tm:, let's add ...

* createdump ([Linux createdump utility](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy))
* *.so (Linux shared object library)
* *.a (macOS archive)
* *.dylib (macOS dynamic library)

Let's base the content on the behavior of the latest SDK. Therefore, we do **NOT** need to version this content after all (i.e., a 2.2 app produced with the 3.1 SDK will have the *.exe* for Windows, for example).

I guess this link for the createdump utility is ok ...

https://github.com/dotnet/coreclr/blob/master/Documentation/botr/xplat-minidump-generation.md#configurationpolicy

... it was linked by a CoreCLR :cat2: in a CoreCLR issue as their documentation for that utility.

**Comment by Rick-Anderson** [comment]
`Pages&dagger; (MVC or Razor Pages apps; if pages aren't precompiled)` 
**would probably MT better as**
`Pages&dagger;  for MVC or Razor Pages apps, if pages aren't precompiled.`

Let me know if I should make that change.

**Comment by guardrex** [comment]
I'll do it. Only will take a sec, and I haven't dug in yet on my next Blazor thing. ☕️

**Pull request merged**
