### PR TITLE
Distributed caching topic update to 3.0

### LINKED ISSUE #12845: Update distributed caching doc for 3.0
* Web Host --&gt; Generic Host: there's a link to a Web Host doc H2 that doesn't exist in the Generic Host doc.
* Update sample app for 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #12845

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1&branch=pr-en-us-14048)

**Are there breaking changes or new API for distributed caching? If not, this doesn't require engineering review.**

* Can't use whole-topic versioning on this one: There are 2.1 vs. 2.2 deltas to maintain.
* New 3.0 sample confirmed working.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
> Can't use whole-topic versioning on this one: There are 2.1 vs. 2.2 deltas to maintain.

Options include:

* use whole topic versioning and have 3 versions.
* Use two topic versioning, 2.1 + 2.2  combined
* Keep what you have

**Comment by guardrex** [comment]
> Use two topic versioning, 2.1 + 2.2 combined

I don't follow ... need an example because nesting isn't possible.

**Comment by Rick-Anderson** [comment]
I forgot about the nesting problem. Probably what you have is best.

**Comment by guardrex** [comment]
I think on this one it's ok to use the individual blocks ... should result in a minimal amount of *pain*  on maintenance later for the team.

**Comment by Rick-Anderson** [comment]
@JunTaoLuo  **Are there breaking changes or new API for distributed caching? If not, this doesn't require engineering review.**

I've reviewed this so I think it's OK to S&M.

**Comment by JunTaoLuo** [comment]
No there hasn't been any changes to distributed caching API.

**Pull request merged**
