### PR TITLE
Fix broken links

### LINKED ISSUE #13059: OnModelCreating symbolic
fix OnModelCreating link on this page :

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2#default-model-configuration

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13059

Thanks @Goldenstarc! :rocket:

### CODE REVIEW

**Comment by guardrex** [comment]
@scottaddie Could be part of a larger problem. The XREFs seem correct. For example, we had `OnModelCreating` in as ...

```
<xref:Microsoft.EntityFrameworkCore.DbContext.OnModelCreating*>
```

... which seems correct ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.onmodelcreating

... yields ...

```html
<meta name="ms.assetid" content="Microsoft.EntityFrameworkCore.DbContext.OnModelCreating*">
```

... and the XREF thingy agrees ...

Capture

It ultimately resolves to this 404 (for `en-us`) ...

https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.dbcontext.onmodelcreating

**Note the "ef" segment there.**

The actual page should be ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.onmodelcreating

**No "ef" segment.**

I propose we fix this for now with this PR that will use relative links. I can either open a followup issue to revert or we could allow these to be updated on the next sweep/update of this doc.

**Comment by guardrex** [comment]
I'm going to go ahead and merge this one given that those links are currently broken in the live topic.

**Comment by scottaddie** [comment]
@guardrex The issue seems to be that 2 APIs match the search criteria. See for yourself: https://xref.docs.microsoft.com/query?uid=Microsoft.EntityFrameworkCore.DbContext.OnModelCreating*

I'm following up on this internally.

**Comment by guardrex** [comment]
Thanks @scottaddie ... If you need me to open/work a follow-up issue to revert these changes, let me know or open+assign me if you like. Alternatively, the next author to sweep this one down the road will probably revert the changes I made here.

**Pull request merged**
