### PR TITLE
File Uploads update to 3.0

### LINKED ISSUE #13344: File Uploads update to 3.0
* `@attribute [RequestSizeLimitAttribute(52428800)]` in the cshtml. https://github.com/aspnet/AspNetCore.Docs/pull/12344/files#r329287769

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

### LINKED ISSUE #14796: Missing class MultipartRequestHelper
@sergiodesousafilho commented on [Thu Oct 03 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/118)

Hello, the class "MultipartRequestHelper" is not implemented or builtin.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Uploads de arquivos no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Thu Oct 03 2019](https://github.com/aspnet/AspNetCore.Docs.pt-br/issues/118#issuecomment-537945387)

Hello, @sergiodesousafilho
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13344
Fixes #14796

[Internal Review Topic](#)

* Whole-topic versioning.
* Confirmed working 3.0 sample.
* Surface `@attribute [RequestSizeLimitAttribute(52428800)]`.
* Surface removal of `FormFileValueProviderFactory` for `DisableFormValueModelBindingAttribute`.
* Update a few 3.0 syntax changes for in-text examples.
* Include the `MultipartRequestHelper` class in the text. It wasn't clear to a reader how that was being handled.

@Rutix to :eyes: first, then we'll just do a docs team review.

### CODE REVIEW

**Comment by Rutix** [comment]
@guardrex I was reviewing and I noticed that a lot was duplicate in the `::: moniker range=">= aspnetcore-3.0"` is this intentional and how does this work? Why do we need to duplicate a lot of the text?

**Comment by guardrex** [comment]
@Rutix Yeah ..... that's a *damned-if-we-do/damed-if-we-don't* thing.

When the versions reference different samples and there are *many* sample links to pull the code in, the topic will flip in-and-out of versioning ranges ... every time there's a sample link. We've also had rapid engineering churn to deal with. We had some topics with tons of complicated version flipping ... so much that it was very hard to maintain the topic (e.g., Kestrel).

This way for each release, we can just duplicate the entire thing ... slap a new version on it ... and update that content.

Obviously, the downside is that if we need to make a change that applies to all versions that we need to make that change multiple times in the topic ... once per versioned section.

There's no easy answer. We can't predict how easy it will be either way for a given topic *in the future*. For now, I guess u could say that we're doing this as a bit of an experiment. It will probably work out ok, but who knows in the end.

**Comment by Legends** [comment]
Is there an MVC counterpart without this Razor Pages?

**Comment by Rick-Anderson** [comment]
We do most of the new samples with Razor Pages. It's pretty easy to migrate to MVC with controllers and views. We don't want to duplicate content.

**Comment by Legends** [comment]
A duplicate would be the same code again, but I guess the MVC api looks different.
Don't discriminate us MVC developers ;-)

**Pull request merged**
