### PR TITLE
Clarify that Visual C++ 2015 Redistributable needs Update 3

### PR DESCRIPTION
**Pull request by jawn**
While the current link is correct, this clarifies the specific version.
This page states the Update 3 is required: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore30

### CODE REVIEW

**Comment by guardrex** [comment]
@jawn I agree on the link text, but there's a potential difference between what .NET Core requires and what the hosting bundle requires. @shirhatti will confirm if this is the best approach going forward (even if this requirement still exists).

**Comment by shirhatti** [comment]
@jkotalik Can you confirm that this is the case?

**Comment by jkotalik** [comment]
I'm not sure at all, but if .NET 3.0 requires Update 3, it's probably a good idea to mention it anyways.

**Comment by guardrex** [comment]
Let's leave it. The hosting bundle installer wanted it. If the machine didn't have an Internet connection and it wasn't installed manually, the dev would :boom:.

Thanks @jawn! :rocket:

**Pull request merged**
