### PR TITLE
Create 3.0-SDK.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
We should be using this for prerequisites.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
cc @serpent5  in #14362

**Comment by guardrex** [comment]
It can't just be ...

```
[.NET Core 3.0 SDK](https://dotnet.microsoft.com/download/dotnet-core/3.0)
```

**Comment by guardrex** [comment]
If we miss the update, it will go stale quickly.

**Comment by scottaddie** [comment]
I'd go with what Luke proposed (to future-proof), but it's fine either way.

**Pull request merged**
