### PR TITLE
Update handle-errors.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fantastic info but way too long to MT (Machine translate).

Avoid safe unless you can define/tell them how to be safe.

After @guardrex  review, we'll bring in the rest of the gang.

Once approved, S&M into #13407

### CODE REVIEW

**Comment by guardrex** [comment]
I'll look first thing on Tuesday morning. The content was already approved by engineering, so I think we can merge after this.

btw - How are you deciding which sentences to break? Has the localization team provided guidance on sentence length or stated that the use of all (or most) non-essential clauses should be avoided?

The problem with breaking sentences to this degree is that it slows down reading. It literally takes longer to read the whole topic. It's plainly a less efficient approach to transferring information.

**Comment by Rick-Anderson** [comment]
25 words max.

> The problem with breaking sentences to this degree is that it slows down reading

True, but it increases the speed of comprehension for most folks, and certainly for folks not familiar with the topic.  Our internal tool flagged all of these and  more.

**Comment by Rick-Anderson** [comment]
Yes we can merge once you verify I didn't change the meaning.

**Comment by guardrex** [comment]
I see. Thanks ..... that's the figure that I didn't remember. I think you did state that figure one day in *ancient .NET Core times* 👴 lol. I just now remembered an old convo about it, but that was *years* ago IIRC.

> Our internal tool flagged all of these and more.

That's not surprising. I've seen about *a bazillion* sentences that wouldn't qualify anywhere near 25 words.

**Comment by guardrex** [comment]
I'm on a 😵 *brain fry* 😵 now, but I'll hit this first thing tomorrow morning.

**Pull request merged**
