### PR TITLE
Added dotnet watch run to ui-class.md

### LINKED ISSUE #9488: Update VSC Create a web project instructions
Determine the preferred workflow for new project creation in VS Code. Update the tutorials accordingly. For example:

[Create a web project](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code#create-a-web-project)

Include #10579 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code#create-a-web-project)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

### PR DESCRIPTION
**Pull request by wadepickett**
Replaced "dotnet run" with "dotnet watch run" so that changes requested in later steps will show.
Fixes #9488

### CODE REVIEW

**Comment by wadepickett** [comment]
@scottaddie, sorry to piecemeal this across two PR's today.

**Comment by Rick-Anderson** [comment]
@wadepickett  I don't think we want to start changing to `dotnet watch run`, we should update tutorials to 3.0 and remove any mention of automatic view compiles.

Don't forget to add `[Internal review URL](get url from details link)` to your PR's.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks.
So close #9488 where it already is?  Open a new one for removing mention of automatic view compiles?  That work?

**Comment by Rick-Anderson** [comment]
#9488 has nothing to do with `dotnet watch run`,  @scottaddie  should own that. We want to make sure we're doing the right work flow for VSC.

**Comment by wadepickett** [comment]
I did check with the pm on workflow as the issue asked on the issue assigned to me.  There wasn't much to go on except the other issue referenced.  The pm suggested dotnet watch run instead of dotnet run for those steps so I was following that.  There must be some miscommunication somewhere. Perhaps I didn't explain the issue well enough to the PM.  Thanks again for the info.  I will back out of the PR.

**Pull request closed without merging**
