### PR TITLE
Update Blazor JS Interop for disposal

### LINKED ISSUE #16682: Avoid memory leaks when invoking .NET instance methods
From @partyelite (moved from https://github.com/aspnet/AspNetCore.Docs/issues/16680) ...

There is nothing in the docs about avoiding memory leaks. I dug through the MS docs and found this link

https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference-1?view=aspnetcore-3.1

It says here that in order to avoid leaking memory, the DotNetObjectReference (used for invoking .NET instance methods from JavaScript) must later be disposed by JS code or by .NET code.

What is the best practice for disposing DotNetObjectReferences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Addresses #16682

* Seems to compose well in the class/component scenario.
* Help me on the JS scenario because in the tests I can't grok the `unimportant`/`object` pattern for `.dispose()` in JS code ...

  https://github.com/dotnet/extensions/blob/master/src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs#L256

  That looks like a contrived test where `.dispose()` isn't actually called client-side (i.e., it looks like a **_simulated_** `.dispose()`). What should be shown there in the context of the examples we're using ...

https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerSample/wwwroot/exampleJsInterop.js#L15-L18

btw -- Not today (but soon), I'll be working https://github.com/aspnet/AspNetCore.Docs/issues/14972 to improve this section/topic. Let's fix this "disposal" issue first, and I'll be back. Also related to this section is @pranavkm issue #14879. @pranavkm, I suggest that I work #14972 first because I might be able to fix both issues at the same time. They seem *very closely* related.

### CODE REVIEW

**Comment by guardrex** [comment]
@mkArtakMSFT There's a :question: on this one. See the opening comment :point_up:.

**Comment by guardrex** [comment]
@mkArtak Indeed ... *last one!* I can't grok how to do the disposal from the JS side. The engineering test seems contrived and doesn't actually show how it's done. I didn't see anyone online explaining it.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please suggest how to dispose an object from JS:? Thanks!

**Comment by guardrex** [comment]
I'm going to go ahead and merge this now with the guidance for disposal in a class or component. I'll merge this and leave the issue open so that we can address disposal from JS later.

**Comment by pranavkm** [comment]
This looks fine btw 👍

**Comment by guardrex** [comment]
Thanks @pranavkm ... If you know how to dispose from the JS-side, I left it on the issue to resolve later ... https://github.com/aspnet/AspNetCore.Docs/issues/16682#issuecomment-585997415. I just wanted to get unblocked for splitting the JS Interop topic on Friday before the *3-day weekend! Woot!* 🏖

**Pull request merged**
