### PR TITLE
Surface App Service .NET Core rollout website

### LINKED ISSUE #15228: Add information about when net core 3.0 might be supported
Right now it says "We hope to make this available soon" which is not enough for me. Giving us an indication will be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #15228

Thanks @sander1095! :rocket:

### CODE REVIEW

**Comment by sander1095** [comment]
Hello!

In the discussion of the comment you say the following:

> The runime and the shared framework for 3.0 are there, so you *can host* a 3.0 app on App Service.

So basically, the confusion is that you can't

**Comment by guardrex** [comment]
I'm not sure I understand what you mean ...

If you want to deploy/host an app that uses the 3.0 runtime and shared framework, *yes* ... all good. FDD (framework-dependent deployments) should ✨ *Just Work*:tm: ✨.

If you want to use the SDK (to build an app), *not yet* ... should roll out soon tho. Their agents may be tied to the SDK ... or not ... and there might be an additional delay after the SDK rolls out for their agents to be updated ... not sure. They would need to remark further on it. You can ask them over there on one of their topics to get a member of that team to respond. We're very *compartmentalized* around here. :smile:

**Comment by sander1095** [comment]
I'm sorry if I am being confusing! 

Your main changes in the commit are as follows:

> .NET Core 3.0 on Azure App Service

> For progress on the rollout of .NET Core to Azure App Service, see the official [.NET Core on App Service](https://aspnetcoreon.azurewebsites.net/) website.

So, if you want to see progress on .NET Core version rollout on Azure App Service, you have to check that link. But you are telling me a different story in your comments:

> If you want to deploy/host an app that uses the 3.0 runtime and shared framework, yes ... all good. FDD (framework-dependent deployments) should ✨ Just Work™️ ✨.

So, .Net Core 3.0 (everything except SDK) _is_ already deployed to azure app service! The only reason why I should keep that website in mind is to check when I can use Azure Pipelines (a completely different product) to actually build my .NET Core 3.0 application!

Considering the article is about migrating from 2.2 to 3.0 , I would find it very useful to know this distinction and that if I have a way to build .NET Core 3.0 applications; I can actually just use them in an Azure App Service. 

So, my proposal is to let the user know that the Microsoft Build Host Agents do not currently support 3.0 out of the box but that it can be done with workarounds (Using the .NET core tool installer task or using a docker image), but if they use the workaround or another build service, they can host their 3.0 application in azure.

**Comment by guardrex** [comment]
> keep that website in mind is to check when I can use

> .NET Core 3.0 applications

We only (mostly) cover building ASP.NET Core apps directly with the SDK (not *all* .NET Core things). Azure Pipeline docs should address their scenarios. That's why I recommend opening an issue with them.

You're correct in that the presence of the SDK, which would be shown by that page, doesn't guarantee that their agents will be there ready to use the SDK when it rolls out. You'll have to take that up with them. We don't cover Azure Pipeline/devops (*much* lol) over here ... a few spots ... sometimes a tutorial or section of a topic. Mostly tho, that's their area with their own people.

I know it seems strange to some devs ... I've had a few devs be like "*Dude! YOU are MS. Help me!*" ... but actually, we're highly compartmentalized here ... for efficiency ... and the fact that we can't know *everything* about every product.

Ask them over there ... I think ... hope 🤞 ... you'll get a good answer. At least they should be able to say that when the SDK does show up in a datacenter if their agents are instantly ready to 🎸 or if there will be a further delay while they do things on their end after the SDK rolls out.

**Pull request merged**
