### PR TITLE
Middleware topic update for 3.0

### LINKED ISSUE #13336: Middleware Overview update to 3.0
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #13336

[Internal Review Topic](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.1&branch=pr-en-us-13968)

* I don't :eye: middleware breaking changes for 3.0 ([filtered Announcements](https://github.com/aspnet/Announcements/issues?q=is%3Aissue+is%3Aopen+middleware+label%3A3.0.0)). Are there any deltas or ideas for new coverage that pertain to middleware?
* Primarily addresses the *Order* section for 3.0 given the changes to `Startup.Configure`.
* Moves the *write.md* topic snapshots to a proper *write/snapshot* folder from the *index/snapshot* folder.
* Since snapshots of code aren't part of a proper sample that anyone will ever see, we can drop the extraneous bits: compiler directives, usings, namespaces, snippets.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@jkotalik I don't think this 3.0 update to the **Middleware** topic needs review - unless there were changes to Middleware in 3.0.  If that's true can we S&M this?  `@anurse` is OOF, so suggest another review if one is needed.

**Comment by Rick-Anderson** [comment]
@jkotalik I don't think this 3.0 update to the Middleware topic needs review - unless there were changes to Middleware in 3.0. If that's true can we S&M this? @anurse is OOF, so suggest another review if one is needed.

**Comment by jkotalik** [comment]
Apologies missed this in my inbox. Thanks!

**Comment by jkotalik** [comment]
cc @Tratcher

**Pull request merged**
