### PR TITLE
Remove extra line

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@pranavkm  you can't have embedded `moniker ranges`.  You're adding that to the 2.1/2.2 section, so it's not required.

**Comment by Rick-Anderson** [comment]
[Register the authorization handlers](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#register-the-authorization-handlers) is the code that needs to be updated.

Can we close this and I'll fix the auth filter replacement?

```
public void ConfigureServices(IServiceCollection services)
{

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>(
        options => options.SignIn.RequireConfirmedAccount = true)
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();

    services.AddRazorPages();

    services.AddControllers(config =>
    {
        // using Microsoft.AspNetCore.Mvc.Authorization;
        // using Microsoft.AspNetCore.Authorization;
        var policy = new AuthorizationPolicyBuilder()
                         .RequireAuthenticatedUser()
                         .Build();
        config.Filters.Add(new AuthorizeFilter(policy));
    });
    // Authorization handlers.
    services.AddScoped<IAuthorizationHandler,
                          ContactIsOwnerAuthorizationHandler>();

    services.AddSingleton<IAuthorizationHandler,
                          ContactAdministratorsAuthorizationHandler>();

    services.AddSingleton<IAuthorizationHandler,
                          ContactManagerAuthorizationHandler>();
}
```

**Comment by pranavkm** [comment]
I hadn't looked at the auth handlers. Here's the section I was trying to update: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#require-authenticated-users

**Comment by Rick-Anderson** [comment]
@pranavkm  yes, that's what I have in my previous comment. I'll close this PR - see #16101

**Comment by Rick-Anderson** [comment]
@pranavkm  this is the problem - right
```
    services.AddControllers(config =>
    {
        // using Microsoft.AspNetCore.Mvc.Authorization;
        // using Microsoft.AspNetCore.Authorization;
        var policy = new AuthorizationPolicyBuilder()
                         .RequireAuthenticatedUser()
                         .Build();
        config.Filters.Add(new AuthorizeFilter(policy));
    });
```

**Pull request closed without merging**
