### PR TITLE
Instructions for accessing a command terminal on Mac

### PR DESCRIPTION
**Pull request by mattielee**
@Rick-Anderson Here is the new file we discussed. 
/cc: @anangaur

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@mattielee  check my commit please.

**Comment by Rick-Anderson** [comment]
@tdykstra  the CLA warning just popped up after I did a commit. I guess that pushed it over the limit. Do you know how *temp* employees sign the CLA? cc @scottaddie

**Comment by Rick-Anderson** [comment]
@mattielee you need to sign the CLA
/cc: @anangaur

**Comment by mattielee** [comment]
@Rick-Anderson Ok I signed it.

**Pull request merged**
