### PR TITLE
Preivew 2 CLI

### PR DESCRIPTION
**Pull request by EdCharbeneau**
Updated CLI command for Preview 2 template

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks @EdCharbeneau, but we'd like to keep the short option there. *The shorter the CLI command the better.* We're trying not to spawn horizontal scrollbars in docs wherever possible. Also, the short options are in use all of the repo ... we use them all the time.

**Comment by EdCharbeneau** [comment]
The version number is still incorrect. I'll submit another PR.

**Comment by guardrex** [comment]
Probably because the last update hasn't gone live yet. I'll check. brb

**Comment by guardrex** [comment]
Here's the update.

https://github.com/aspnet/AspNetCore.Docs/pull/15527/files

**Pull request closed without merging**
