### PR TITLE
Adding article describing the use of NCache as an ASP.NET Core SignalR Backplane

### PR DESCRIPTION
**Pull request by Obaid-Rehman**
Hello,

This article explains how NCache can be used as a SignalR backplane to scaleout a SignalR app. NCache is a distributed cache that could be used for object caching, session caching, EF Core provider etc. Following  are the main points of the article:

1- The NCache APIs and NuGet package to include in your app code to set up NCache as a backplane.

2- Configuration options included in an NCache client configuration file that determine the NCache client-server communication behavior.

3- Reliability of NCache backplane using the replication strategies employed in NCache cluster topologies.

4- Logging NCache backplane operations.

### CODE REVIEW

**Comment by guardrex** [comment]
Hello @Obaid-Rehman ... This will be handled by management and SignalR pros.

**Comment by Rick-Anderson** [comment]
@bradygaster  is this something you want to maintain?

**Comment by BrennanConroy** [comment]
Suspiciously related:
https://github.com/aspnet/AspNetCore.Docs/pull/16957

**Comment by Rick-Anderson** [comment]
I think this works better as a blog. @bradygaster  please respond.

**Comment by bradygaster** [comment]
Agreed with @Rick-Anderson - I think this would be better on your site rather than on the official ASP.NET docs. Unless there's some reason we can't, i'd be happy linking to your article, but we'd need it to be maintained and for you to reach out to us with ample time to remove the link if you deprecate. As far as supporting an official doc on it, I'd prefer we not sign up for this (it would be a first for our already-stretched-think collective documentation efforts).

**Pull request closed without merging**
