### PR TITLE
Create CODE_OF_CONDUCT.md

### LINKED ISSUE #15289: Add Create CODE_OF_CONDUCT.md
Clean up lang if possible

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Copy/paste of https://github.com/dotnet/docs/blob/master/CODE_OF_CONDUCT.md

That's a long and difficult to parse sentence. Can we break it up?

Fixes #15289

### CODE REVIEW

**Comment by mairaw** [comment]
That's the standard used in the .NET repos: https://github.com/dotnet/corefx/blob/master/CODE-OF-CONDUCT.md

**Comment by mairaw** [comment]
I'd ping @jongalloway if we want to standardize on a different message for the code of conduct file.

**Comment by Rick-Anderson** [comment]
I just want to use the standard for our org. But that sentence is difficult to understand and I'm sure it MT terribly.

**Comment by mairaw** [comment]
I don't disagree with you. Here's what MicrosoftDocs uses:
https://github.com/MicrosoftDocs/azure-docs/blob/master/CODE_OF_CONDUCT.md

@JasonCard I don't see that file in the loc repos.

**Comment by Rick-Anderson** [comment]
> @JasonCard I don't see that file in the loc repos.

Is that because it's missing from this repo?

**Comment by Rick-Anderson** [comment]
>  Here's what MicrosoftDocs uses:
https://github.com/MicrosoftDocs/azure-docs/blob/master/CODE_OF_CONDUCT.md

Much better.  

Merging this for now. Hopefully we can standardize on  https://github.com/MicrosoftDocs/azure-docs/blob/master/CODE_OF_CONDUCT.md

**Comment by JasonCard** [comment]
@mairaw @Rick-Anderson We were not sure if CODE_OF_CONDUCT.md should be localized or not, so it was on hold. I'll follow up on this question and get back to you.

**Comment by Rick-Anderson** [comment]
I'm not sure either. I just merged into live so you should have the english version soon. @jongalloway  probably knows.

**Comment by mairaw** [comment]
Since you localize the contributing file, I'd probably localize this one as well.

**Comment by JasonCard** [comment]
@mairaw That's a good point, I'm going to go ahead and have the CODE_OF_CONDUCT.md localized in HT. It looks the same for .NET and ASP.NET, so once it's localized for one, then translation can be recycled. cc @Rick-Anderson

**Pull request merged**
