### PR TITLE
Call out header for Linux/Nginx+Blazor Server

### LINKED ISSUE #12107: Surface Blazor/SignalR WSS guidance
[EDIT by guardrex to update the topic metadata: This work will be for the Blazor Server host and deploy topic]

When hosting a server-side Blazor application the following headers should be added in NGINX proxy config or other preferred config to avoid WSS errors under chrome.

proxy_pass http://hellomvc/;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $host;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eddf2de-7e50-5680-ff2d-a4307f26b5c0
* Version Independent ID: 673f220c-ad49-bd27-5d74-3a9c44747cba
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.0#signalr-configuration)
* Content Source: [aspnetcore/host-and-deploy/blazor/server.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by guardrex**
Fixes #12107

This is untested (by me), and idk if a similar config applies to Apache. I can't find *any* Linux guidance in the SignalR topics.

It looks like the primary guidance here is for the `Connection` header because the rest of the suggestion on the issue matches what we have in the Linux Nginx hosting coverage. Over there, we show ...

```
proxy_pass         http://localhost:5000;
proxy_http_version 1.1;
proxy_set_header   Upgrade $http_upgrade;
proxy_set_header   Connection keep-alive;
proxy_set_header   Host $host;
proxy_cache_bypass $http_upgrade;
proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header   X-Forwarded-Proto $scheme;
```

... so on this PR, I just call out the `Connection` header being set to `$http_connection`.

### CODE REVIEW

**Comment by guardrex** [comment]
@shirhatti I think this one is a quick review. If not tho, it can wait.

**Comment by guardrex** [comment]
@shirhatti Are u back. This is a quick one if the guidance is correct.

**Comment by shirhatti** [comment]
Connection upgrade is a hop-by-hop header and I'm just not familiar enough with this. I'd refrain from merging until someone has had the opportunity to validate this.

**Comment by guardrex** [comment]
This post and SO answer support not using `keep-alive`:

* https://medium.com/@alm.ozdmr/deployment-of-signalr-with-nginx-daf392cf2b93
* https://stackoverflow.com/questions/48300288/signalr-in-asp-net-core-behind-nginx

Mozilla text quoted by the author ...

> If you need to create a WebSocket connection from scratch, you'll have to handle the handshaking process yourself. After creating the initial HTTP/1.1 session, you need to request the upgrade by adding to a standard request the Upgrade and Connection headers, as follows:

```
Connection: Upgrade
Upgrade: websocket
```

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism

**Comment by danroth27** [comment]
@anurse Thoughts on this one?

**Comment by anurse** [comment]
Yep, you definitely have to configure nginx to proxy WebSockets, it doesn't by default. This is a good article to reference: https://www.nginx.com/blog/websocket-nginx/

(Honestly we should have something like this in SignalR docs too, we just haven't had time ;)).

I believe you need **both** of these (the `Connection` header alone is insufficient):

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

**Comment by guardrex** [comment]
> Honestly we should have something like this in SignalR docs too,

I'll see if I can add it on this PR.

**Comment by guardrex** [comment]
@anurse I don't see a super-clean spot for it, so I place it at the bottom of the SignalR *Host and scale* topic.

Would you also like it in the *Publish to Azure Web App* topic?

**Pull request merged**
