### PR TITLE
OData tutorial

### LINKED ISSUE #11770: Odata Documentation
I want to add a few articles (and code examples as well) about Odata support in ASP.net core so as required in CONTRIBUTING.md file for complex submissions i opened this issue to get approval for them.
what i have in mind is a simple example of adding odata capabilities on top of existing API and also some tips for scenarios which include  starting a new API project  with odata support from scratch.
also i come across this (https://github.com/aspnet/Docs/issues/9740) open issue about odata so i was wondering should i do it or wait for odata official team.
also i think it worth to mention that im having 1.5+ years experience with ASP.net core and 3+ years experience with C# and ASP.net mvc (.net framework) and also good understanding of odata.

@Rick-Anderson  edit:

Reopen this and PR #12108 When https://github.com/MicrosoftDocs/OData-docs/pull/74 is merged. Look for closed issues with ODATA `in:title`

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-odata-api?view=aspnetcore-2.2&branch=pr-en-us-12108&tabs=visual-studio)

Fixes #11770

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@FIVIL  can you help me with this?

```
    app.UseMvc(routeBuilder =>
    {
        routeBuilder.EnableDependencyInjection();
        routeBuilder.Select().OrderBy().Filter();
    });
```
The preceding code:

* Enables DI for the route builder.
* Enables select, order by, and filtering to the route builder.

**Comment by FIVIL** [comment]
@Rick-Anderson 
sure, what should i do to help you?

**Comment by Rick-Anderson** [comment]
After showing the following code
```
    app.UseMvc(routeBuilder =>
    {
        routeBuilder.EnableDependencyInjection();
        routeBuilder.Select().OrderBy().Filter();
    });
```

I added this to the doc. Is that correct? Can you suggest better?

The preceding code:

* Enables DI for the route builder.
* Enables select, order by, and filtering to the route builder.

**Comment by FIVIL** [comment]
@Rick-Anderson 
actually, this enables an override to the existing endpoints through dependency injection, instead of having traditional `\OData` endpoint.
however, considering this tutorial aims beginners i think what you wrote is perfect. going through details of `routbuilder` can a bit confusing.

**Comment by Rick-Anderson** [comment]
@FIVIL  should we be using EDM like [this blog](https://devblogs.microsoft.com/odata/asp-net-core-odata-now-available/)

**Comment by FIVIL** [comment]
@Rick-Anderson 
EDMs are good for security reasons but they are not necessary.
as I mentioned in the issue (https://github.com/aspnet/AspNetCore.Docs/issues/11770) I want to submit 2 sets of articles. and I wish to go in depth in the second ones. I will cover EDM  in them.
for this article, I wanted to show how you can add OData with as less as modification in existing codes.

**Comment by Rick-Anderson** [comment]
@hassanhabib please review

**Comment by FIVIL** [comment]
Hi, i was wondering when this gets merged and if there is anything else i can help with?
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@FIVIL  I'm waiting for the product unit to review this. Hopefully in the next couple of week. I really appreciate your help on this.

**Comment by FIVIL** [comment]
@Rick-Anderson Sure, i see
thank you

**Comment by Rick-Anderson** [comment]
@danroth27  should I delete these two OData articles?

**Comment by Rick-Anderson** [comment]
@danroth27 should I delete these two OData PR's? This and #12150

**Pull request closed without merging**
