### PR TITLE
C95509: Escaping "|"

### PR DESCRIPTION
**Pull request by v-makoud**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

### CODE REVIEW

**Comment by guardrex** [comment]
@v-makoud Can you provide the link to the live topic that has bad rendering?

Because that vertical bar is inline code, it's rendering ok here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers-middleware-options

If we do need to apply a fix, I recommend a different approach that changes the character outside of our build system (`&vert` with `<code>` tags):

> \<code>ForwardedHeaders.XForwardedFor \&vert; ForwardedHeaders.XForwardedProto\</code>

**Comment by v-makoud** [comment]
#sign-off

**Comment by guardrex** [comment]
Do you have the link to the localized topic that was reported by the reader?

**Comment by guardrex** [comment]
@v-makoud Let's not do this unless we take a look at the localized topic and see how it breaks there. This change shouldn't be necessary ... *in theory*. :smile: lol

Let me know if you get the link to the localized topic so that we can take a closer look. If we need to do something, we can re-open this PR and continue.

**Pull request closed without merging**
