### PR TITLE
Fix nameof arguments in User model

### PR DESCRIPTION
**Pull request by natstar93**
FirstName and LastName were the wrong way round

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
Fixes #13230

@natstar93  thanks for this fix.

**Comment by pjdennis** [comment]
FYI this change has been reverted: https://github.com/aspnet/AspNetCore.Docs/pull/14732/commits/a4cb90c57bf913f723e0c20c0d6859d08acfa5ce

See: https://github.com/aspnet/AspNetCore.Docs/issues/14731 and https://github.com/aspnet/AspNetCore.Docs/pull/14732

**Comment by Rick-Anderson** [comment]
@serpent5 please review

**Comment by Rick-Anderson** [comment]
It's looks like this PR was wrong.

**Comment by serpent5** [comment]
@Rick-Anderson Yeah, this one appears to have been incorrect. Would you like me to update the sample project to include a working example of exercising this stuff?

**Comment by Rick-Anderson** [comment]
> Would you like me to update the sample project to include a working example of exercising this stuff?

That would be great. Create an issue to track

**Pull request merged**
