### PR TITLE
v3 preview 4 update to core vs 4.x compare

### PR DESCRIPTION
**Pull request by wadepickett**
Updated this comparison doc to account for ASP.NET Core 3.0 Preview 4.    The compare doc uses an include called benefits.md which was also updated.  Minor updates overall.

Current published version of this doc:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-3.0

### CODE REVIEW

**Comment by wadepickett** [comment]
Blazor or Blazor (Preview):  Checking with the PM, thanks Tom.

**Comment by wadepickett** [comment]
@danroth27, at this point in time should we include (Preview) after "Blazor"?

**Comment by danroth27** [comment]
Blazor only appears in the 3.0 preview doc set, so I think preview is implied and doesn't need to be stated in prose.

**Comment by wadepickett** [comment]
@tdykstra, PM says "Blazor" is the most appropriate here.  Good catch though, thanks for asking.

**Comment by wadepickett** [comment]
@tdykstra, I thought this PR went through.  Looking back I realized it is still showing build/license checks did not complete for some reason.  Also no option to merge.  What am I missing?  Thanks for looking.

**Pull request merged**
