### PR TITLE
3.0 first Web API

### LINKED ISSUE #12461: Should HTTPS redirection occur earlier in the pipeline?
Might be an ID-10T error on my part, but I'm working up a Blazor sample for web API and using the sample app here as a basis. With the sample app's pipeline order of ...

```csharp
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseHttpsRedirection();
app.UseMvc();
```

... the *Index.html* page loads (handled by Static File Middleware prior to the HTTPS Redirection Middleware), but the GET (and any other method, POST, etc.) throws a CORS violation (browser) and a 'method not supported' exception from endpoint middleware (app) due to (*I think*) the redirect working on the subsequent requests (handled by MVC after HTTPS Redirection Middleware) ... thus a protocol change on the AJAX requests.

Whether that's a correct interpretation or not ... If the order is changed for a redirect to the secure protocol on the initial *index.html* page request, then subsequent requests to GET, POST, etc. work fine (protocol is the same). Should the order in the pipeline be? ...

```csharp
app.UseHttpsRedirection();
app.UseDefaultFiles();
app.UseStaticFiles();
app.UseMvc();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### LINKED ISSUE #13373: 3.0 Update: Create a Web API
3.0 update Update: Create a Web API 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### LINKED ISSUE #13482: 3.0 update: Fix jQuery
Fix jQuery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
[Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&branch=pr-en-us-13311&tabs=visual-studio)

partial #13372
Fixes #13373 
Fixes #12461
Fixes #13482

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@scottaddie  can you fix `samples\3.0\TodoApi\wwwroot\site.js` so the jQuery works. Only add/delete work.  Edit doesn't work.

**Comment by scottaddie** [comment]
@Rick-Anderson The HTTP POST method works now. Assigning back to you, in case there's anything else you want to do with this PR.

**Comment by Rick-Anderson** [comment]
@scottaddie muchas gracias
So it was string "1" vs int `1`

**Comment by scottaddie** [comment]
@Rick-Anderson Yes. The call to jQuery's `val` function returns a string. The C# property is of type `long`, so I casted the string to a number with the JavaScript `parseInt` function.

**Pull request merged**
