### PR TITLE
Document [Consumes].

### LINKED ISSUE #6295: Add documentation for MVC's [Consumes] attribute
See https://github.com/aspnet/Mvc/issues/7755

We're missing coverage of `[Consumes]` which is an attribute developers can use to limit an action to handling a set of specified content types, or choose a different action based on the request content type.

### PR DESCRIPTION
**Pull request by serpent5**
`@Rick-Anderson  edit` Moved to #16871

Fixes #6295.

Before I continue with this, I've got a couple of questions:

1. Is it OK to just have the 3.x sample code, but display it for all monikers? The code is _exactly_ the same for all versions.
2. Should the explanation (to be added) include a walkthrough of how to test this using the httprepl? I don't think it's needed, but it was suggested in the linked issue.

cc @scottaddie

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
*1. I vote yes for 1, just the 3.x code.
* 2. I think an outline, not a walkthrough, would be nice for how to test.

**Comment by serpent5** [comment]
Let me know if you'd rather I didn't request reviews. I saw the option, which is nice, but I don't wanna be pushy...

**Comment by Rick-Anderson** [comment]
That's fine.

**Comment by serpent5** [comment]
> That's fine. It won't happy today being the biggest holiday in the USA.

Of course, that's fine. I'm not trying to get things reviewed quickly. I'm just making sure the right people know about it. I've no problem with how long it takes. Ultimately, you guys own this. I'm just grateful if you take my stuff at all. :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
