### PR TITLE
Update @aspnet -> @microsoft

### LINKED ISSUE #13007: Rename '@aspnet/signalr' and '@aspnet/signalr-protocol-msgpack' to '@microsoft/...'
Rename '@aspnet/signalr' and '@aspnet/signalr-protocol-msgpack' to '@microsoft/...'

https://github.com/aspnet/AspNetCore/issues/11568

### PR DESCRIPTION
**Pull request by mikaelm12**
[EDIT by @guardrex to add docs issue]

Fixes #13007

Reaction to https://github.com/aspnet/AspNetCore/issues/11568
Updating @aspnet -> @microsoft

### CODE REVIEW

**Comment by scottaddie** [comment]
@mikaelm12 This new npm package is marked as a "placeholder package". When does the team plan to publish it to npm? We'll need to coordinate that with the merging of this PR.

**Comment by mikaelm12** [comment]
Yes sorry, I should have clarified in the pr description. The change is set to take place for preview 7.

**Comment by guardrex** [comment]
Retarget for the `release/3.0-preview7` branch?

**Comment by scottaddie** [comment]
@mikaelm12 Thank you for the clarification. Can you please use the `release/3.0-preview7` branch for this change?

**Comment by mikaelm12** [comment]
Okay, sounds good. I will probably close this and open a new pr since just changing the base here doesn't make for a clean merge

**Pull request closed without merging**
