### PR TITLE
Loc fix - add monikers for APS.NET Core 3

### PR DESCRIPTION
**Pull request by dksimpson**
Loc fix for story [1583925](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1583925/).

### CODE REVIEW

**Comment by dksimpson** [comment]
#sign-off

**Comment by Rick-Anderson** [comment]
See the [Internal review URL](https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.0&branch=pr-en-us-13875#hosting-startup-assemblies)

image

We don't use nested monikers. I thought they were not allowed.

**Comment by Rick-Anderson** [comment]
@dksimpson  why is this a loc issue?

**Comment by guardrex** [comment]
The versioning isn't correct (i.e., we don't support <2.1). More important, this is the **_Web Host_** topic, and I'm not aware of that composition (`ConfigureWebHostDefaults`) for Web Host at 3.0. Best to ask @tdykstra about that. Everything I'm doing right now goes with Generic Host for 3.0; and IIRC, I don't have any 2.2 samps that call `UseSetting` where this would apply. It might be correct, but I have no knowledge on it at this time.

@Rick-Anderson You're correct on versioning: *No nesting of moniker ranges.*

**Comment by Rick-Anderson** [comment]
@JasonCard  this comes from https://github.com/aspnet/AspNetCore.Docs.es-es/pull/32
I think it's much more efficient for source PR's to remove the loc middleman and ask the customer to create a PR in our repo. Google translate works good enough.

**Comment by guardrex** [comment]
@Rick-Anderson I have a few minutes to take a closer look. Tea leaves right now are that `ConfigureWebHostDefaults` isn't a `WebHostBuilderExtensions` extension. I'll report back in a bit.

**Comment by guardrex** [comment]
*Yep* ... the reader is conflating the Generic Host and Web Host builder extensions. To quote D🦆, *This isn't a thing ... the reader made this up.* :smile:

**Pull request closed without merging**
