### PR TITLE
Add a sample for circuit handler

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by guardrex** [comment]
@pranavkm Ok ... I think we're good ... do you want to put one more :eye: on mi nittolas??

**Comment by Rick-Anderson** [comment]
@guardrex  can we S&M. We can always update if we get feedback.

**Comment by guardrex** [comment]
Code changes ... I need @pranavkm to look. I'm here ... not going anywhere. I'll S&M the second he gives it a :+1:.

**Comment by guardrex** [comment]
@Rick-Anderson Were u wanting to go live now with the latest batch of PRs?

**Comment by Rick-Anderson** [comment]
@guardrex  no, just checking.

**Comment by pranavkm** [comment]
Yup, looks 👍

**Comment by Rick-Anderson** [comment]
@pranavkm  can you look at #16703 ?

**Pull request merged**
