### PR TITLE
Compressed .PNG image files

### PR DESCRIPTION
**Pull request by IEvangelist**
Hi friends 👋 !

I executed an image compression algorithm over your repo -- using **pngquant**, recursively optimizing PNG image file sizes. We went from 25.7 MB to 10.1 MB for the 620+ image files in this PR, here are the totals:

| Before | After |
|--------|-------|
| 25.7 MB (26,975,632 bytes) | 10.1 MB (10,683,835 bytes) |

**Saving a total of 16,291,797 bytes (16.3 MB), 2.5x smaller** /cc @scottaddie

### CODE REVIEW

**Comment by scottaddie** [comment]
Thank you for helping out with this, @IEvangelist!

**Comment by Rick-Anderson** [comment]
Can you revert this ? It's causing lots of errors. See https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C332f35cd-658d-4914-0f85-907e40ee89f0%5CPullRequest%5C202012170128273371-20971%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v1c4lWUE%2Bx1jxAHfnYDpYTRzKeAgCcuSvY6WYOMTMzg%3D&st=2020-12-17T01%3A24%3A44Z&se=2021-01-17T01%3A29%3A44Z&sp=r

cc @guardrex

**Comment by Rick-Anderson** [comment]
@IEvangelist  @scottaddie  @guardrex   Got a  million errors on png, closed PR rebuilt and errors went away.

**Comment by IEvangelist** [comment]
I was not worried about this PR, it has been in place for over a year now - and hasn't been an issue. Why would it all of a sudden cause problems? Happy you were able to figure it out.

**Comment by scottaddie** [comment]
@Rick-Anderson The related messages in the build report pertain to invalid file links and missing alt text. As far as I can tell, the image compression has been working quite well.

**Comment by LayersOfAbstraction** [comment]
I was able to compress images other than .png in my own website portfolio using Calibre Actions and when I look at the images and screenshots heading in the [contribution guidelines.](https://github.com/dotnet/AspNetCore.Docs/blob/13303f8ff3ebea353f859808c5084cc54051643a/CONTRIBUTING.md#:~:text=Visual%20Studio%20extension.-,Code%20snippets,earlier%20for%20sample%20projects.,-The%20following%20examples)
I notice newcomers are told to use their own image compression tools. 

What if I automate the process by implementing a GitHub Action so .jpg, .jpeg and .webp image formats are automatically compressed upon a PR with a new image? 

Not trying to say we should scrap the originally approved changes here or anything. Just that we automate the process of compressing other image formats.  

Also if you accept that, I was wondering if in the guidelines I could then just change this: 

```
As an optional step, ensure that any images and screenshots used in the documentation are compressed, which helps with file size and page load performance. A few popular tools include TinyPNG (using the TinyPNG website or the TinyPNG API) or the Image Optimiser Visual Studio extension.
```

To this.

```
Our site automatically compresses images and screenshots used in the documentation, so any compression on your part is unnecessary. A few popular tools that were used before we automated the process include TinyPNG (using the TinyPNG website or the TinyPNG API) or the Image Optimiser Visual Studio extension.

Just to make contributions easier for others, especially first-timers. No point in doing more compressions if it's done automatically.

**Comment by Rick-Anderson** [comment]
I don't think it's worth the effort. It's so rare that folks contribute images.

**Pull request merged**
