### PR TITLE
Add VS download campaign links

### PR DESCRIPTION
**Pull request by scottaddie**
Fixes https://github.com/aspnet/AspNetCore.Docs/issues/12377

Also deletes 2 related, unused includes.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
cc @tdykstra

**Comment by scottaddie** [comment]
@Rick-Anderson I like the idea of an include for VS 2019. Should that be handled in a separate PR?

**Comment by Rick-Anderson** [comment]
We need to get rid of all screen shots except on onboarding tutorials. We're better off having VS17 screenshots and listing VS19 - at least VS19 works with the current SDK. We can open issues to remove the sccreenshots.

Remove all the VS17 links in this PR.

**Comment by scottaddie** [comment]
@Rick-Anderson Please take another look.

**Pull request merged**
